### ISSUE TITLE
1.2.7.1

### ISSUE THREAD

**Issue by man4781747** [KanaHayama/KanCollePlayerSimulator#10]
你好 1.2.7.1中關聯出擊的等待士氣恢復倒數的時間似乎不太正確
例如: 我已設定目標值45 艦隊中所有船艦是其皆大於45 但倒數時間依然會有好幾分鐘
似乎還是會要等到恢復成49

**Comment by KanaHayama** [comment]
经测试，我没有遇到你说的问题。

+ 游戏服务器上士气的刷新时间是每3分钟，因为不知道服务器那边具体的刷新时间点，所以等待时间是3的倍数向上取整。肯定会比实际时间要长至多3分钟。
+ 等待时长以判断的时间点的数值为准，那个时点算出来是几分钟就等待几分钟，即使之后出现了所有船的士气高于设定值，剩的时间依然会等完不会重新调整。
+ 你的这个issue的标题光写个版本号没有概括问题内容，不合适。1.2.7.1版中这里没有调整过，以前版本里什么样，这个版本就什么样。

**Comment by man4781747** [comment]
了解 辛苦了
可能是我細部還沒弄熟的關係
很想買序號支持大大 可是目前付費的方式台灣這邊會比較難支付... 我試了幾種目前都失敗...
所以對不起大大目前只用免費版QQ

Kana <notifications@github.com> 於 2019年2月15日 週五 上午5:22寫道：
