### ISSUE TITLE
执行变更装备时检查到错误

### ISSUE THREAD

**Issue by Archerfrank8** [KanaHayama/KanCollePlayerSimulator#100]
**Version**
1.5.0.7

**Describe the bug**
无法执行所有与装备相关的动作，自带的泊地修理编成也一样

控制台提示
 ERROR “4-1”中的“基础变更装备”报错，已自动禁用：
    执行变更装备时检查到错误
        Value cannot be null. (Parameter 'value')

**Frequency of the bug**
在更新1.5.0.7之前，1.5.0.6使用正常，但是突然出现这个bug，遂试图更新1.5.0.7，但是症状一样

**Comment by KanaHayama** [comment]
这个报错手动刷新一下游戏应该就可以解决

**Comment by Archerfrank8** [comment]
刷新就好了，谢谢奏大
