### ISSUE TITLE
27日维护后无法派出远征

### ISSUE THREAD

**Issue by david446747602** [KanaHayama/KanCollePlayerSimulator#11]
如题

**Comment by KanaHayama** [comment]
我目前没有遇到你说的问题。
请添加详细描述。

**Comment by david446747602** [comment]
远征发出界面不会点击远征开始按钮；接收远征时会卡在远征成功界面。

**Comment by KanaHayama** [comment]
本次游戏维护并没有改变游戏UI，所以并没有可能维护后会卡住。
应该是个别情况。请打开设置中的超时重试功能。
请确保程序为最新版本，还不好使的话可以使用“数据工具”尝试匹配相应“页面”来定为问题。

**Comment by KanaHayama** [comment]
另外[《已知问题》](http://kcps.info/?page_id=184)中提到过一个可能导致接受远征时卡住的问题以及解决方法。
