### ISSUE TITLE
部分海图（尤其从E5开始），陆航无法选到点

### ISSUE THREAD

**Issue by Dan1ui** [KanaHayama/KanCollePlayerSimulator#112]
**Version**
The KancollePlayerSimulator Kai version (shown in the title of the main window) of the bug occurs.

**Describe the bug**

**Frequency of the bug**
Is the bug occurs occasional or fixed? How often?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete all of the following information):**
 - OS: [e.g. Windows]
 - OS version [e.g. 10.0.14393]
 - OS language: [e.g. Simplified Chinese]
 - Browser: [e.g. poi]
 - Browser version: [e.g. 9.0]
 - KCPS bowser plugin version: [e.g. 1.0.0]
 - Is KCPS registed: [e.g. No]
 - Game account level: [e.g. 120]

**Additional context**

**Comment by Dan1ui** [comment]
版本1.5.1.4，经常是陆航点了第一队第一波之后就卡住不动了

**Comment by KanaHayama** [comment]
很可能是你设置有问题。我使用这个版本打了整个活动，没遇到任何问题。

**Comment by Dan1ui** [comment]
> 很可能是你设置有问题。我使用这个版本打了整个活动，没遇到任何问题。

![选取点击范围 2023_10_2 13_12_10 (2)](https://github.com/KanaHayama/KanCollePlayerSimulator/assets/64205089/42bfd3cf-2049-4495-9b15-987c810f0d61)

这样框有问题吗？真的死活选不到

**Comment by KanaHayama** [comment]
飞机航程不够也没法选

**Comment by Dan1ui** [comment]
> 飞机航程不够也没法选

我怎么可能连航程都不知道，可以手选

**Comment by KanaHayama** [comment]
这我就不清楚了。可以换个分辨率试试
