### ISSUE TITLE
2023.10.3  23夏活 E4 M点 联合舰队二队旗舰存在大破进击，单次出击模块设置，伴随舰大破 ：强制撤退

### ISSUE THREAD

**Issue by silverAnswerer** [KanaHayama/KanCollePlayerSimulator#113]
Version
The KancollePlayerSimulator Kai version (shown in the title of the main window) of the bug occurs.
1.5.1.4

Describe the bug
23夏活 E4 M点 联合舰队二队旗舰存在大破进击，单次出击模块设置，伴随舰大破 ：强制撤退
![e4m夕张大破](https://github.com/KanaHayama/KanCollePlayerSimulator/assets/40844668/4b7989d7-6523-45d1-8ac7-b2f471309292)
![N点F5](https://github.com/KanaHayama/KanCollePlayerSimulator/assets/40844668/9ace820c-18f2-454e-bf64-1f8edfc5e4f0)

Frequency of the bug
Is the bug occurs occasional or fixed? How often?
目前只观察到一次

To Reproduce
使用关联出击模块

Expected behavior
不会撤退，正常进击E4-N点

Environment (please complete all of the following information):

OS: 	Windows 11 家庭中文版
OS version 22H2   22621.2283
OS language: 简体中文
Browser: poi
Browser version: 10.9.2
Game account level: 116
Additional context
poi缩放100%

**Comment by silverAnswerer** [comment]
N点f5了 第二个图是N点的战斗记录截图

**Comment by yubanmeixiao** [comment]
从联合舰队机制诞生截止到目前为止，并没有出现过联合舰队二队的旗舰因为大破而被击沉的报告。
所以目前的共识是二队旗舰可以大破进击。
自然不会撤退

**Comment by silverAnswerer** [comment]
好的  谢谢告知

**Comment by KanaHayama** [comment]
是的，“伴随舰大破”设定不适用于联合舰队二队旗舰，这是当初很多用户要求的功能，也确实再历次活动中挺有用的。我默认二队旗舰大破不会沉是个游戏常识。
