### ISSUE TITLE
那个，活动快结束了，还不更新地图资料吗？

### ISSUE THREAD

**Issue by yubanmeixiao** [KanaHayama/KanCollePlayerSimulator#114]
_(:3 」∠)_因为没开会员的关系，我的QQ目前才挂到28级，进不了群。
所以一直在等官方的更新……
现在活动都快结束了 ∑(°口°๑)

**Comment by sscs0192** [comment]
提供自製的檔案，先確保你可以訪問Google雲端。
https://drive.google.com/drive/folders/1SZ-FX-7AIda-ipi5-fKRZ1emvaBtKOKp?usp=sharing

**Comment by yubanmeixiao** [comment]
> 提供自製的檔案，先確保你可以訪問Google雲端。 https://drive.google.com/drive/folders/1SZ-FX-7AIda-ipi5-fKRZ1emvaBtKOKp?usp=sharing

3Q，我有梯子

**Comment by yubanmeixiao** [comment]
> 提供自製的檔案，先確保你可以訪問Google雲端。 https://drive.google.com/drive/folders/1SZ-FX-7AIda-ipi5-fKRZ1emvaBtKOKp?usp=sharing
![1KPFYV0R0R0FS8XU7{XDO5C](https://github.com/KanaHayama/KanCollePlayerSimulator/assets/59812878/1e5688ff-9694-4cb3-ac7b-0501b0793cb5)
搞定了

**Comment by sscs0192** [comment]
祝你活動愉快，如果有什麼問題再通知我。

**Comment by yubanmeixiao** [comment]
> 祝你活動愉快，如果有什麼問題再通知我。

好嘞哥

**Comment by KanaHayama** [comment]
因为我打活动打得很晚，所以我做好后活动都快结束了，所以基本没有发布的必要了。
