### ISSUE TITLE
綁定錯誤的解除時間是否可以縮短？

### ISSUE THREAD

**Issue by sscs0192** [KanaHayama/KanCollePlayerSimulator#117]
有時候注冊伺服連不太上，程式又蠻常與伺服連線檢查，偶發會連轉換成試用(連線失敗)都沒發生直接卡住無法操作，不得以需要強制關閉程式，但注冊碼綁定錯誤又會卡住三小時才會解除，想請開發者是否減少注冊伺服訪問的頻繁度或者減少注冊碼綁定錯誤需要等待三小時的時間？

**Comment by KanaHayama** [comment]
正常使用时不应该经常出现这种状况。这个时间无法缩短，因为我购买的注册服务中没有提供修改这个时间的选项。它们直接在文档里写这个时间就是3小时。
我自己没有做注册服务是因为这种服务要租防DDoS服务器，成本高到不可能考虑。
