### ISSUE TITLE
2024 2/29 維修後大破未自動結束繼續進擊

### ISSUE THREAD

**Issue by envy1990** [KanaHayama/KanCollePlayerSimulator#118]
**Version**
The KancollePlayerSimulator Kai version 1.5.2.0 of the bug occurs.

**Describe the bug**
2024 2/29 維修後大破未自動結束繼續進擊

**Frequency of the bug**
經常

**Expected behavior**

**Screenshots**

**Environment (please complete all of the following information):**

 - Browser: Poi 10.9.2

**Additional context**

**Comment by KanaHayama** [comment]
感谢汇报。详情以及近况更新请关注《已知问题与FAQ》。

**Comment by envy1990** [comment]
經過觀察似乎是無法讀取被開幕雷大破的結果導致繼續進擊
已7-1為例
在第一點被開幕雷大破後依然進擊
如果在第二點水雷戰鬥後大破會撤退回港
不管還請仔細確認，感謝

**Comment by KanaHayama** [comment]
问题的原因就是开幕雷的API改了，所以poi检测不出来了，然后导致kcps也检测不出来了。说实话，除了等poi本体（非未卜先知插件）更新，没有特别好的办法。

**Comment by KanaHayama** [comment]
我上传了修复了该问题的poi版本，在poi发布正式更新解决这个问题之前请使用我上传的poi版本。详情请参阅《已知问题与FAQ》。

**Comment by envy1990** [comment]
已下載使用，感謝
