### ISSUE TITLE
无法自动选择阵型

### ISSUE THREAD

**Issue by ChristopherSung** [KanaHayama/KanCollePlayerSimulator#12]
![image](https://user-images.githubusercontent.com/49830879/56847773-433e6080-6912-11e9-957b-a8ec217263ae.png)
单独测试单次出击单元时无法自动选择阵型，需手动选择后程序才可继续。不手动选择阵型也无报错

**Comment by KanaHayama** [comment]
文字描述是“**单次**出击”，然而截图里报错的是“**关联**出击”。
应该是你不会使用造成的问题，不是程序本身的问题。
发布这么久了，其他人那里没有听说过这个基本的功能出现过不能用的问题。
建议参考范例配置，学习使用方法，或者使用范例配置测试功能。

**Comment by ChristopherSung** [comment]
我尝试重新安装软件、清空魔改文件，并按照你写的使用说明配置出击，无法自动选择阵型。
购买服务后使用你的范例配置出击依旧无法自动选择阵型。

**Comment by KanaHayama** [comment]
之前可以用的话，就回忆一下你改过什么导致它不好用了
