### ISSUE TITLE
活动图跳转页面 潜在路径经验证不可用

### ISSUE THREAD

**Issue by Tyrantsloth** [KanaHayama/KanCollePlayerSimulator#120]
**Version**
1.5.2.0

**Describe the bug**
总控出击活动图，活动图第一页潜在路径经验证不可用，导航失败

**Frequency of the bug**
总是

**To Reproduce**
1、执行带出击期间限定海域单元的总控
2、总控刷新后自动点击出击按钮
3、自动点击期间限定海域按钮
4、加载期间限定海域第一页画面时（此时右下角在转圈圈）
5、发生报错

**Expected behavior**
正常识别期间限定海域并执行出击、总控流程

**Screenshots**
![image](https://github.com/KanaHayama/KanCollePlayerSimulator/assets/30263490/ae222c58-084b-4c72-9155-51cb7514157a)

**Additional context**
手动进入期间海域第一页后，单独执行出击单元，可以正常执行翻页点击E3区域等操作，说明手动录入的海域地图和跳转按钮PNG识别正常。
**怀疑是点击期间海域按钮后，在转圈加载时进行了海域识别**，导致无法正确识别海域信息？
比较明显的就是在出击单元执行“出击按钮”-->delay-->“期间海域按钮”过程中，快速手动点击“期间海域按钮”即可正常进入后续出击流程。
类似的是总控流程出击E1、E2时，log会报基地航空队按钮不存在，应该也是识别问题。

**Comment by KanaHayama** [comment]
活动海域需要自行适配才可出击，不适配无法出击。我用自己做的图能打到E4，所以说明程序没有问题。请检查自己制作的图像是否有问题。

**Comment by KanaHayama** [comment]
另外补充一下，你可能没有适配翻页按钮的图像。

**Comment by Tyrantsloth** [comment]
已适配了翻页按钮的图像。
补充描述中有说明：手动进入期间限定海域（第一页）后，直接执行出击单元，程序是可以正常翻至第二页页、点击E3海域并走完出击单元的；但是放在总控流程里执行出击单元就会报如上错误

**Comment by Tyrantsloth** [comment]
额，后续又仔细看了下，应该是活动page1_A适配阈值设置过大，导致在常规图海域即去判断活动区域翻页按钮，自然找不到对应潜在路径。
减小阈值后，适配正常。
