### ISSUE TITLE
部分新船及新改造船无法自动更换装备

### ISSUE THREAD

**Issue by kimibsb** [KanaHayama/KanCollePlayerSimulator#121]
**Version**
1.5.2.0

**Describe the bug**
自动出击更换装备时，无法更换装备报错，目前已发现此问题出现在伊41及三隈改二特上。

**Screenshots**
以下是log记录：
关联出击前改装执行单元执行时出现了错误，因未设置相关错误处理方式而无法继续
        One or more errors occurred. (The navigation 'Ship.Class' cannot be loaded because one or more of the key or foreign key properties are shadow properties and the entity is not being tracked. Relationships using shadow values can only be loaded for tracked entities.)
![Screenshot 2024-03-31 115917](https://github.com/KanaHayama/KanCollePlayerSimulator/assets/14835638/ab6cbb35-f251-4adf-82bb-13613d3bac33)

**Environment (please complete all of the following information):**
 - OS: Windows 11
 - OS version 10.0.0.22631
 - Browser: poi
 - Browser version: 10.9.2
 - KCPS bowser plugin version: 1.5.2.0

**Comment by KanaHayama** [comment]
请去下载KCPS的地方下载新的数据库文件。
