### ISSUE TITLE
伊41改裝錯誤

### ISSUE THREAD

**Issue by sbd0517** [KanaHayama/KanCollePlayerSimulator#124]
**Version**
1.5.2.0

**Describe the bug**
只要試圖對伊41改裝，就算裝備是伊41能裝的，基本上都會報錯。

**Frequency of the bug**
總是會發生。

**To Reproduce**
只要對伊41改裝就會發生。

**Expected behavior**
比如：
2024/4/11 下午 05:34:43 +08:00	“2-2練級”中的“基礎變更裝備”报错，已自动禁用：
    执行变更装备时检查到错误
        One or more errors occurred. (The navigation 'Ship.Class' cannot be loaded because one or more of the key or foreign key properties are shadow properties and the entity is not being tracked. Relationships using shadow values can only be loaded for tracked entities.)

**Environment (please complete all of the following information):**
 - OS: Windows
 - OS version 11
 - OS language: 繁中
 - Browser: poi
 - Browser version: 10.9.2
 - KCPS bowser plugin version: 1.4.7
 - Is KCPS registed: ?
 - Game account level: 110

**Comment by KanaHayama** [comment]
请按照FAQ中的提示替换数据库文件。请不要重复提问。谢谢。
