### ISSUE TITLE
1.2.7.5无法发出远征

### ISSUE THREAD

**Issue by ChristopherSung** [KanaHayama/KanCollePlayerSimulator#13]
![image](https://user-images.githubusercontent.com/49830879/59097290-c27e7580-894f-11e9-89b8-baffde882152.png)

**Comment by KanaHayama** [comment]
我之后会处理这个问题。
你把8号远征开出来，就正常了。

**Comment by ChristopherSung** [comment]
![image](https://user-images.githubusercontent.com/49830879/59110487-d33fe300-8971-11e9-9b9c-e11b0ae7944f.png)
远征均处于已解锁状态（仅作反馈）

**Comment by JacHammer** [comment]
相同问题。
第二舰队发任何镇守府海域的远征都会在远征发出页报错。

弹窗：
![image](https://user-images.githubusercontent.com/24962354/61126768-984a3700-a46a-11e9-84dc-575a637d6488.png)

报错log输出：
![image](https://user-images.githubusercontent.com/24962354/61126638-3ee20800-a46a-11e9-9594-88ab86449cf1.png)

操作环境：
所有远征已解锁，poi 10.2.4 兼容模式windows 7
OS:  Windows 10 Enterprise x64 1903
CPU: AMD Ryzen 7 2700
MB: ASUS X470-I
RAM: 16GB
GPU: RTX 2080 驱动430.64

**Comment by KanaHayama** [comment]
> 相同问题。
> 第二舰队发任何镇守府海域的远征都会在远征发出页报错。
> 
> 弹窗：
> ![image](https://user-images.githubusercontent.com/24962354/61126768-984a3700-a46a-11e9-84dc-575a637d6488.png)
> 
> 报错log输出：
> ![image](https://user-images.githubusercontent.com/24962354/61126638-3ee20800-a46a-11e9-9594-88ab86449cf1.png)
> 
> 操作环境：
> 所有远征已解锁，poi 10.2.4 兼容模式windows 7
> OS: Windows 10 Enterprise x64 1903
> CPU: AMD Ryzen 7 2700
> MB: ASUS X470-I
> RAM: 16GB
> GPU: RTX 2080 驱动430.64

请问仅这个版本，你之前成功跑过第二舰队远征吗？
我看不到图片，请问是在远征的哪个阶段（画面）报的错？
点关于页面中的清空缓存后是否仍然不好使？

**Comment by JacHammer** [comment]
@KanaHayama 
1. 第二舰队试过可以跑远征9，20和21不停，但是第二舰队跑任何镇守府海域的远征都会汇报上述错误
2. 出击->远征->出现选择远征界面后报错
3. 清空API缓存之后重启程序依旧出现bug

**Comment by KanaHayama** [comment]
> @KanaHayama
> 
> 1. 第二舰队试过可以跑远征9，20和21不停，但是第二舰队跑任何镇守府海域的远征都会汇报上述错误
> 2. 出击->远征->出现选择远征界面后报错
> 3. 清空API缓存之后重启程序依旧出现bug

1.2.7.6里发出远征的逻辑做了改动。请问这个版本里你那里运行也会出这个问题吗？

**Comment by JacHammer** [comment]
@KanaHayama 
我还在1.2.7.5版本的时候不知道怎么的又好了。我记得我调整了以下环境：
POI左下角的自动调整；
分辨率从67%调至100%；
更换了POI显示设置->布局；
解锁刷新率限制。原先限制在30Hz

目前1.2.7.6发旧镇守府远征没有问题
