### ISSUE TITLE
20190809bug汇报/建议

### ISSUE THREAD

**Issue by bugreport0809** [KanaHayama/KanCollePlayerSimulator#16]
[更换装备]
1.190810版本更新后无换装疑问了。但还请适配“全装备解除（卸下）”功能。

[流程卡死]
1.与已在问题描述中写的不同，绝大多数时间能正常工作的流程，“即使不勾选WINAPI选项”也有一定几率出现卡住且无刷新无报错的情况。log无更多内容。

[建议]
1.希望能增加一个能够弹窗且**有系统声音提示**的触发型执行单元（类似于原1-1无法换船之后的报错），可用于提示用户当前流程执行完毕。
2.可否能增加一个保存已有模板阈值的功能？在公司与家里2套环境下（分辨率CPU等均不同），入渠阈值都要改为460，D败阈值都要改为18。但现在每次更新都需要重改一遍。

**Comment by KanaHayama** [comment]
卸下全部装备功能经考虑，没有优雅的适配方案，再考虑到它用处不大，因此功能上线时就决定不提供，之后也没有提供的计划。除非大量用户需求极其强烈。

卡死问题我只遇到过超时重试不停打log并重试，但实际并无重试动作，游戏依然卡在母港。经查是poi端的问题，并非脚本的问题，目前除了试着换74EO试试之外没有解决方案。你log无内容是否是因为没有开超时重试？正常情况下操作失败会被超时重试功能重试，所以不用担心。

你可以使用此次新增的自动停止后Python入口，使用Python代码实现自定义的提示功能，不论是弹窗还是放音乐还是打电话还是发短信，比单独提供执行单元功能要强大得多。新增专用执行单元这一点我会再考虑。

解决自定义阈值与发布版本阈值冲突的问题之前就已经排上日程，但优先级不高，因为需求不大。你可以发邮件告诉我具体哪些模板的阈值不够用，并附带此时的游戏png截图，我确认不是你电脑自身问题的话，我下次发布的时候会改成合适的阈值。

**Comment by bugreport0809** [comment]
1.3.4明白了。
关于4可否给一个邮箱地址？

2.跟今天提的一个issue差不多的情况。
我这边是允许120秒重试，允许刷新，poi端，没开winapi。
人没有操作游戏甚至有时候不在电脑前。流程可能跑了20，30个循环就卡在各种不同的地方，补给，罗盘，出击前刷新或出击前（即当前任务显示了，但看log也只卡在当前任务）等。频率不定，可能一天无状况也可能半小时内就卡2-3次。
