### ISSUE TITLE
1.3.0.3自动出击卡在阵型选择

### ISSUE THREAD

**Issue by ChristopherSung** [KanaHayama/KanCollePlayerSimulator#17]
![image](https://user-images.githubusercontent.com/49830879/62927199-a03e2380-bde8-11e9-9eea-38377885247a.png)
自动出击转完罗盘后卡在阵型选择页面，也没有任何报错。这个问题之前几个版本就一直存在

**Comment by KanaHayama** [comment]
检查系统字体有没有被改动过。
你也可以使用《数据工具》检查对应页面是否能够正常匹配并用PhotoShop等软件比较具体差异。
