### ISSUE TITLE
换装备bug

### ISSUE THREAD

**Issue by bugreport0809** [KanaHayama/KanCollePlayerSimulator#18]
神威改母设定将装备更换为+0特二式内火艇的时候会换成强风改，反复测试几次可复现。
同时吕500可正常更换+10特二式内火艇。

**Comment by KanaHayama** [comment]
请运行配套资料中的排查换装备错误用python脚本然后报告脚本给出的具体出错信息。

**Comment by bugreport0809** [comment]
运行脚本后报错……已输入舰船ID

报错如下：

![QQ图片20190907180306](https://user-images.githubusercontent.com/53931526/64473478-0163d780-d19a-11e9-8185-16f1609926ec.png)

**Comment by KanaHayama** [comment]
检查了一下，是缺组件了。
你把这个dll放到程序文件夹里再试吧。
[IronPython.Modules.zip](https://github.com/KanaHayama/KanCollePlayerSimulator/files/3587140/IronPython.Modules.zip)

**Comment by bugreport0809** [comment]
谢谢。
因为不知道为何截图一直传不上来，相关信息及截图均通过邮件发送了。
请查收。

**Comment by KanaHayama** [comment]
收到

**Comment by KanaHayama** [comment]
写给后面看到这个issue的人：
排查出现问题的装备是
零式水中听音机

**Comment by KanaHayama** [comment]
我发现我没有零式水听，所以没法验证外部数据。只能等我想办法搞一个之后再处理了。

**Comment by bugreport0809** [comment]
补充一句1310版本前这个是正常的。

**Comment by KanaHayama** [comment]
请问1.3.2版本是否还存在这个问题？没有的话请关闭issue

**Comment by bugreport0809** [comment]
奏大好：

目前测试中零听可正常更换，已关闭issue。


Kana <notifications@github.com> 于2019年11月28日周四 上午3:30写道：

**Comment by bugreport0809** [comment]
有两个新的问题还请看一下，也已经提交issue。

阈值汇报 <cyued5907@gmail.com> 于2019年12月2日周一 上午10:51写道：
