### ISSUE TITLE
一个换装备时的偶发性BUG

### ISSUE THREAD

**Issue by bugreport0809** [KanaHayama/KanCollePlayerSimulator#19]
在自动换装备时，可能出现如下现象：

设定为"为2/3/4/5/6"位的船更换装备时，偶尔会错误地将1号位的船更换装备。
重新触发模块可正常更换，疑似偶尔没有等待画面稳定就开始换装。

**Comment by KanaHayama** [comment]
我用了这一个月，没有遇到过你说的状况，遇到的话再说。
