### ISSUE TITLE
接收远征后，没有进入补给界面，直接进入了远征界面，然后报错

### ISSUE THREAD

**Issue by huiyiygy** [KanaHayama/KanCollePlayerSimulator#2]

**Comment by KanaHayama** [comment]
你都开了临时补给功能了，那为什么要进补给页面？没开的才会进补给页面。报错和进不进补给页面没关系。

预览的这个这个版本又没怎么测试，报错多了去了，不知道你说的是报了什么错。已知bug见发布页面。
