### ISSUE TITLE
希望基础变更装备模块增加“第一次启动时清空此舰队所有船的装备”功能

### ISSUE THREAD

**Issue by ArchmageTony** [KanaHayama/KanCollePlayerSimulator#20]
希望基础变更装备模块能够增加一个选项“第一次启动时清空此舰队所有船的装备”。
看了wiki目前好像没有报告说这个事情，所以想提一下建议，希望大佬能够采纳。
目的是因为某些比较苛刻的情况可能会导致变更装备报错。
举例：
若只有一架强风改水战，需要变更日进的装备。
日进目前身上的装备：炮，炮，炮，**强风改**
日进脚本更换装备为：炮，炮，**强风改**，炮
这个时候就会报错：XXXX经筛选后没有可用的装备。因为这件装备实际上是在日进的第四个格子里面。
***
这个可以使用逻辑判断下是不是装备的位置有问题，但是还是希望能够增加第一次清空装备的功能。

**Comment by KanaHayama** [comment]
这个问题我记录下来了，目前的建议是多备几个装备。问题有些棘手，但会尝试解决。我理想的解决方案应当不用“清空装备”这么大动干戈而且把状态搞得更复杂的方式。
