### ISSUE TITLE
从上午开始忽然提示当前注册码已在线。

### ISSUE THREAD

**Issue by bugreport0809** [KanaHayama/KanCollePlayerSimulator#21]
电脑未更换硬件，一直是一台电脑。
每25分钟可登录1次，但正常关闭后再打开必然显示注册码在线。
尝试过重装KCPS（及旧版本），更换注册码，均无效。

**Comment by KanaHayama** [comment]
我前天为了调试调整过一次注册服务的设置项，效果不好，所以昨天已经恢复了原设置。
我不知道你为什么现在还会遇到这个问题。

**Comment by bugreport0809** [comment]
之前KCPS卡死时，可以在“后台进程”中找到（并关闭）。
现在启动时只有应用中可以看到，是正常的吗？

而且现在可以同时开多个KCPS，过去一直会报错显示“已有一个实例在运行”

**Comment by KanaHayama** [comment]
我不清楚你说的“只有应用中可以看到”是指的什么。

据我了解其他出现这个情况的人那里，昨天已经恢复正常了。我判断不出你这里是出了什么问题。

**Comment by bugreport0809** [comment]
过去（不是经常会因为别的原因卡死嘛，比如直接点击拆船模块，直接点击单次编成等，）关闭kcps并ctrl+alt+del之后，能够在win10任务管理器“后台进程”里看到kcps进程。现在我ctrl+alt+del之后，任务管理器只有“应用”里能够看到kcps，后台进程里是没有的。我不知道正常情况下是不是这个现象。

截止到目前为止，我已尝试过重装poi10.3/10.4版本，重装kcps1305/1310版本，尝试第二个注册码重新激活，均无效。现在还是这样。

是不是这件事与我本地并无关系，而是你那边服务器上有些问题？

**Comment by Zhuager** [comment]
同样发生一打开软件就显示“注册失败。Error,当前注册码已在线,如非法退出请等待1500秒.”
PS: 1500秒是不是有点长了

**Comment by KanaHayama** [comment]
> 同样发生一打开软件就显示“注册失败。Error,当前注册码已在线,如非法退出请等待1500秒.”
> PS: 1500秒是不是有点长了

我要声明一下，我是用的现成的注册服务。
①这个中英文糅合并且使用“非法退出”这种莫名其妙描述的错误提示不是我写的，是注册服务写死的。
②1500秒不是我设置的，是注册服务写死的。
以上内容以及延伸讨论在互助群里已经发生过一次，我不想再重复讨论。
现在的情况就是我早已经把选项改回去了，不会再出现登不上的情况了才对。你们出现这类问题的，重启电脑再试。

**Comment by bugreport0809** [comment]
口说无凭，我已遵循你的建议，再次使用刚刚从git上下载的1.3.1.0版本，分别在两台不同硬件配置不同网络环境下的电脑上（其中有一台工作用机根本与舰C无关），使用两个不同的注册码，执行了解压——成功注册——右下退出——重启的流程。结果仍然是，注册失败。以下为两个不同注册码的证据：

![QQ图片20191015222059](https://user-images.githubusercontent.com/53931526/66840491-b8722080-ef9a-11e9-9ae9-32f729a82cfe.png)
![QQ图片20191015222207](https://user-images.githubusercontent.com/53931526/66840501-bdcf6b00-ef9a-11e9-92c7-54d94c1d24ff.png)
![QQ图片20191015222129](https://user-images.githubusercontent.com/53931526/66840515-c2941f00-ef9a-11e9-9e8b-a797dbca1692.png)

不仅如此，在下午我已反复进行过重启/重新开机/重置路由/配置VPN/更改DNS等等所有可能与网络问题相关的尝试。虽然我不是技术，但起码我是个产品，凡事自己先动手鼓捣几下这个我还是知道的。

我们的目的是来解决一个现在仍然在发生的问题。你是商家，我们是客户，本应该相互信任而不是简单粗暴把问题归结于用户头上。我们并没有质疑你把选项修改回去，而你也不该用“不想重复”“你重启”这类语言来搪塞我们。

**Comment by KanaHayama** [comment]
抱歉让你折腾了那么多遍，我看群里几个报错的人都说好了，没想到你还会遇到这个问题并且愿意尝试那么多组合。
之前那个回复说不想再讨论是因为之前群里讨论讨论就变成了“非法注册是什么鬼”、“为什么是1500秒”、“为什么要用这个垃圾注册服务”、“我为什么不自己写一个注册服务”、“DDos攻击怎么防”、“国庆墙变高了国外为什么就不能提供稳定服务”，虽然讨论过程很友善，谈因为太花时间了，所以我不想再在Github上解释一遍。
报bug这种事其实互助群里多见，github上不多我处理起来不熟练。

**Comment by bugreport0809** [comment]
收到，我已发送邮件给你。
