### ISSUE TITLE
最新版本换装备功能出现问题

### ISSUE THREAD

**Issue by lanshanxuying** [KanaHayama/KanCollePlayerSimulator#23]
最新版1.3.2.0中换装备出现‘object reference not set to an instance of an object’

这个报错是在更新为1.3.2.0后才出现的，换用回1.3.1.0版本后不出现该错误

**Comment by bugreport0809** [comment]
我前两天跟你一样
那天恰好有事重装了系统之后复现不出来
我就把自己提交的ISSUE关了

既然你也说了那我也证实一下
有这个情况
而且是活动前出现的

**Comment by lanshanxuying** [comment]
> 我前两天跟你一样
> 那天恰好有事重装了系统之后复现不出来
> 我就把自己提交的ISSUE关了
> 而且当天出现的时候，重开程序，重启机器，都解决不了
> 我记不清自己出问题时候是不是没装库？你要不要试试重装库
> 
> 顺便补充一个问题
> 我这给阿布鲁齐公爵换装的时候，会自动把第一槽的装备换上然后立刻卸下，导致
> ![QQ图片20191202095406](https://user-images.githubusercontent.com/53931526/69925164-b7b13180-14e9-11ea-8a54-9cdc54ce8e61.png)
> 
> 把设置改成“未使用装备优先”后，会换上别的错误的装备。
> 使用脚本跑了一下外部数据没有出错，非常奇怪

我的两个库都装了，而且不装库是没法打开最新版本的，应该不是这个问题

**Comment by KanaHayama** [comment]
已找到问题原因，详见当前的《已知问题》
