### ISSUE TITLE
多个问题汇报

### ISSUE THREAD

**Issue by start1223** [KanaHayama/KanCollePlayerSimulator#26]
问题1：
![QQ图片20191224014501](https://user-images.githubusercontent.com/59177027/71372642-e8b7ea00-25ef-11ea-9520-925d2d35d0ae.png)
![QQ图片20191224014538](https://user-images.githubusercontent.com/59177027/71372751-36cced80-25f0-11ea-98c9-0f7306c5315e.png)

如图所示，朝霜改二的可装备列表内错误出现了 5inch 単装高角砲群。
这件装备应该被分类为高角副炮，驱逐舰不可装备。
目前在驱逐舰可装备列表内出现，导致后续装备换错。

问题2：
目前仍有乱换装备的问题。
设定为：
![QQ图片20191224180758](https://user-images.githubusercontent.com/59177027/71408210-5871b780-2678-11ea-909e-ac44282cc35f.png)
观察到会换正确装备后立刻卸下，然后换上根本无关的装备。
如这样：
![QQ图片20191224180920](https://user-images.githubusercontent.com/59177027/71408268-89ea8300-2678-11ea-8e72-a6fb76849342.png)
用脚本看外部数据是正常的。

问题3：
自从更换.net core平台后，软件自身变得卡顿，掉帧。例如点击打开/保存配置时都需要5-10秒，关闭配置的提示窗口会先听到声音然后过一会窗口才弹出来。（但执行的时候并不卡）。
界面也变成了这个样子。
![QQ图片20191224181307](https://user-images.githubusercontent.com/59177027/71408518-83104000-2679-11ea-804c-1fce0b9f328f.png)

建议1：
由于poi10.4.0正式版在部分环境下存在一些影响使用的问题，poi很快推出了10.5.0beta来尝试解决。
但poi10.5.0使用了electron7.1.5，与KCPS插件无法兼容。
不知可否能够同时提供2个版本的KCPS插件分别支持正式版与测试版呢？不然都只能用有bug的poi10.4.0了。

**Comment by KanaHayama** [comment]
下次请不要把多个问题放到同一个issue里，我会不知道什么时候去关闭它。

换装备的问题请去下载本体的地方，我上传了一个ExtraData.json，你用它替换/data下的同名文件后，重开程序再试试看。

卡顿的问题我这里没有发生反而是换了.net core版本后运行流畅了很多。你重新解压到别处（就是不带default.json），看看还卡不卡？

poi的问题已经通过发布新版插件解决。

**Comment by start1223** [comment]
明白，下次会将问题分开提交。

问题1：新版ExtraData.json已简单测试了一下，脚本里能识别到正确的数据。

问题2：仍未解决，描述一下具体现象：
使用脚本跑了一下夕张改二特的外部数据，是完全正确的，包括昨天发放的新甲标都可以识别到。
但是执行换装时会换上错误的装备。
设置为夕张第4，5两格分别为“新型高温高圧缶”和“GFCS Mk.37”。
但是反复重试发现，无论是直接换装还是清空所有装备重新换装，都会被换上喷2和13对空电探。
确认地图缓存和陆航缓存刷新过。

问题3：使用了一段时间后卡顿掉帧消失了……
但是打开关闭/保存配置的弹窗仍然有一个很高的延时。

**Comment by KanaHayama** [comment]
1.3.3.2已解决能解决的所有问题
