### ISSUE TITLE
龙田改二换装问题

### ISSUE THREAD

**Issue by dusollst** [KanaHayama/KanCollePlayerSimulator#27]
**Version**
The KancollePlayerSimulator Kai version (shown in the title of the main window) of the bug occurs.
1321版，使用的1.26上传的数据包

**Describe the bug**
在龙田改二的换装里多出了三类装备

1. 8cm，8cm增设，10cm，10cm增设这些高脚副炮
![image](https://user-images.githubusercontent.com/46520981/73533282-67a70a80-4459-11ea-894b-9ba4ee02fe2f.png)

2. 排在sk早期型之后的 中大型电探
包括21 32 42 fumo电探

3. 侦察机类，龙田改二只能装备旋翼机 不能装备零式水侦之类的普通侦察机
![image](https://user-images.githubusercontent.com/46520981/73533315-7d1c3480-4459-11ea-9f0b-2ac33f8ca9c6.png)

**Environment (please complete all of the following information):**
 - OS: [e.g. Windows] Windows
 - OS version [e.g. 10.0.14393] 
 - OS language: [e.g. Simplified Chinese] 简体中文
 - Browser: [e.g. poi] poi 
 - Browser version: [e.g. 9.0] 10.5.1
 - KCPS bowser plugin version: [e.g. 1.0.0] 1.4
 - Is KCPS registed: [e.g. No] Y
 - Game account level: [e.g. 120] 115

**Comment by glanzchristian** [comment]
夕张改二的四五装备格也有一样的问题

**Comment by start1223** [comment]
日向的第四格也出现了这个问题。
所有中口径和大口径都被错误列在可用列表内。

目前看来就是这些“特定船”的“特定格子”需要进行特殊处理。

**Comment by KanaHayama** [comment]
@start1223 没错，一直都是特定船和特定格子特别处理的，但没人试过的话就不知道哪些船和哪些格子是特殊的，以及特殊在哪里

**Comment by start1223** [comment]
嗯嗯明白。
顺便补充一下：
是伊势日向“改二”的第四格和第五格。我上面没写清。
这四个格子的限制相同，都是带不了主炮。

**Comment by KanaHayama** [comment]
@dusollst @glanzchristian @start1223 
试试1.3.3.2
