### ISSUE TITLE
2月7日游戏更新后，入渠会报错

### ISSUE THREAD

**Issue by glanzchristian** [KanaHayama/KanCollePlayerSimulator#28]
**Version**
The KancollePlayerSimulator Kai version (shown in the title of the main window) of the bug occurs.

**Describe the bug**
游戏更新后，入渠会报Exception of type "KancollePlayerSimulatorKaiCore.UnknownShipSortMethodException" was thrown.
目测是因为这次更新了入渠UI，新加了按修理时长排序舰娘造成的原因

**Environment (please complete all of the following information):**
 - OS: Windows
 - OS language: [e.g. Simplified Chinese]
 - Browser: poi
 - Browser version: 10.5.1
 - KCPS bowser plugin version: 1.4.0
 - Is KCPS registed: Yes
 - Game account level: 116

**Comment by KanaHayama** [comment]
临时解决方案已经加入[《已知问题与FAQ》](https://github.com/KanaHayama/KanCollePlayerSimulator/wiki/%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98%E4%B8%8EFAQ)

**Comment by KanaHayama** [comment]
已更新
