### ISSUE TITLE
检查更新时会报错

### ISSUE THREAD

**Issue by start1223** [KanaHayama/KanCollePlayerSimulator#29]
![QQ图片20200210122055](https://user-images.githubusercontent.com/59177027/74120802-cf024e80-4bff-11ea-87df-8361b6eb6d12.png)

**Comment by KanaHayama** [comment]
请检查你的计算机不使用代理的情况下到Github的连接是否稳定

**Comment by start1223** [comment]
测试结果：
1.我到github是可以直连的，包括手机直连，没有任何问题。
2.试着开了一下全局代理，然后检查更新，仍然报错。

**Comment by KanaHayama** [comment]
是Win10吗？

**Comment by start1223** [comment]
是的，WIN10 1909。

**Comment by start1223** [comment]
1402版本不再出现该现象。
