### ISSUE TITLE
更新到最新版本以后执行程序每次都会卡在编成那一步

### ISSUE THREAD

**Issue by sekurodesu** [KanaHayama/KanCollePlayerSimulator#30]
如题，更新到最新版本以后执行程序每次都会卡在编成那一步，获取舰船数据还是和以前一样用poi的舰娘信息复制出来

**Comment by KanaHayama** [comment]
有没有log？
具体卡住的表现是什么？
重新创建编成执行单元并执行后是否有同样的问题？

**Comment by sekurodesu** [comment]
log和卡住的表现我都上传到附件里了，辛苦奏大看一下，重新创建单元试了也还是一样会卡住

Kana <notifications@github.com> 于2020年2月15日周六 上午9:40写道：

**Comment by sekurodesu** [comment]
而且还有一个问题，这次更新以后，打1-6的话，进击到最后一个点了以后，会卡在那个界面，不会自动点掉回母港，具体log我也上传到附件图里了

Kana <notifications@github.com> 于2020年2月15日周六 上午9:40写道：

**Comment by KanaHayama** [comment]
抱歉忘了回复。看来Github没有自动把邮件附件放到回复附件的功能，我看不到附件，你能上github的回复栏传一下附件吗

**Comment by sekurodesu** [comment]
![1](https://user-images.githubusercontent.com/51750095/74832167-97d22280-530e-11ea-8c50-0b35400cdab3.PNG)
![2](https://user-images.githubusercontent.com/51750095/74832175-9acd1300-530e-11ea-8799-c0242374a220.PNG)
![3](https://user-images.githubusercontent.com/51750095/74832184-9d2f6d00-530e-11ea-9f55-2efe6d8bf948.PNG)
![4](https://user-images.githubusercontent.com/51750095/74832187-9ef93080-530e-11ea-943a-478508944c85.PNG)
1,2,3这三张图是编成卡住的相关图，4图是打1-6时到达终点后卡在那个界面，不会自动点掉回母港时的log

**Comment by KanaHayama** [comment]
你这UI怎么和我的不一样啊。不多说了不许UI魔改了吗

**Comment by KanaHayama** [comment]
我试了，5个内置UI模式没一个是长你这样的。
所以确定你这是UI魔改了，这个Issue就没意义了，关了。
