### ISSUE TITLE
升级工具到1.3.3.0版本后，启用任意执行单元都会报错

### ISSUE THREAD

**Issue by karegyudon** [KanaHayama/KanCollePlayerSimulator#31]
**Version**
1.3.3.0

**Describe the bug**
升级工具到1.3.3.0版本后，启用任意执行单元都会报错，报错截图请参考下方。

**Frequency of the bug**
每次启用执行单元都会发生。

**To Reproduce**
随便启用一个执行单元就发生

**Expected behavior**
1.3.3.0之前的版本都可以正常工作。

**Screenshots**
![bug](https://s2.ax1x.com/2020/02/19/3ATdT1.jpg)

**Environment (please complete all of the following information):**
 - OS: Windows 10 1809
 - OS version [10.0.17763.864]
 - OS language: [Simplified Chinese]
 - Browser: [poi]
 - Browser version: [10.5.1]
 - KCPS bowser plugin version: [1.4.0]
 - Is KCPS registed: [Yes]
 - Game account level: [120]

**Additional context**
无

**Comment by KanaHayama** [comment]
OpenCV 4.2默认使用了AVX指令集，导致升级了OpenCvSharp后遇到不支持AVX指令集的电脑会报错。
1.3.3.1版本已经降级到旧版OpenCvSharp。
