### ISSUE TITLE
04/02出现 Capture failed (status code InternalServerError)

### ISSUE THREAD

**Issue by lee76827** [KanaHayama/KanCollePlayerSimulator#33]
昨日之前皆还可运行正常
但今日04/02一早启动则出现
Capture failed (status code InternalServerError)

无论远征还是其他都会出现
也确认过浏览器、插件、软件版本皆已是最新版本

![1585790055985](https://user-images.githubusercontent.com/63027621/78200817-62e6ed00-74c2-11ea-9c88-0dbe0ceda1ce.jpg)

**Comment by KanaHayama** [comment]
照着FAQ里写的，看看poi控制台上插件报了什么错

**Comment by lee76827** [comment]
> 照着FAQ里写的，看看poi控制台上插件报了什么错
不好意思，个人不太了解这英文是啥意思

若是指错误提示：“获取数据失败：×××××××”
Console选项是这样的
![1585796710691](https://user-images.githubusercontent.com/63027621/78206588-d7755800-74d1-11ea-9a84-8f4a9a311996.jpg)

若是指错误提示：“Pointer xxxx failed (status code InternalServerError)”
插件中唯一能勾选的选项我是没勾的
检查更新，插件已是１.4.0
poi检查更新已是10.5.1

**Comment by KanaHayama** [comment]
可能是你5277这个端口被占用了，检查一下或者重启再试

**Comment by KanaHayama** [comment]
请问问题是否已经解决，已经解决的话我就把这个issue关掉

**Comment by KanaHayama** [comment]
两个月过去了，请问这个问题是否已经解决了？已经解决的话请关掉issue。
注：插件的WIN API功能仅支持正式版poi。
