### ISSUE TITLE
夕张改二特换装备时会出现神秘BUG

### ISSUE THREAD

**Issue by start1223** [KanaHayama/KanCollePlayerSimulator#34]
为夕张改二特第四格换装备的时候，会出现如下现象：

目标：换装2个高温高压缶，其中一个需要在第四格。
1.从0开始换装（身上没有高温高压缶的时候），在更换第2个（就是第四格那个）的时候会报错
2020-04-02 16:42:03,402 ERROR “北方海域警备3-2”中的“出击前换装备”报错，已自动禁用：
执行变更装备时检查到错误:
Value does not fall within the expected range.

2.尝试为第一二格换2个缶，正常。尝试为第一二四格换3个缶，换到第3个缶时再次报错。

3.身上已有1个高温高压缶的时候，换装不会出错。

4.使用排查脚本看了一下第四格的备选项，全部都是正确的。

**Comment by KanaHayama** [comment]
外部数据未适配，需等待适配。
正在开发的版本已可以自动从该错误中恢复，之后会择机发布。
