### ISSUE TITLE
1.4.0.2 JPEG质量100%，工厂建造报错

### ISSUE THREAD

**Issue by QPass** [KanaHayama/KanCollePlayerSimulator#35]
**Version**
The KancollePlayerSimulator Kai version (shown in the title of the main window) of the bug occurs.
1.4.0.2

**Describe the bug**
JPEG质量100%，工厂建造报错

**Frequency of the bug**
Is the bug occurs occasional or fixed? How often?
每次

**To Reproduce**
运行范例脚本到每日建造的步骤

**Expected behavior**
完成建造

**Screenshots**
![image](https://user-images.githubusercontent.com/41622253/80272106-2e4d0680-86f9-11ea-9dde-27b30208eaec.png)

**Environment (please complete all of the following information):**
 - OS: [e.g. Windows]win10 1909
 - OS version [e.g. 10.0.14393]18363.592
 - OS language: [e.g. Simplified Chinese]SC
 - Browser: [e.g. poi]poi
 - Browser version: [e.g. 9.0]10.5.1
 - KCPS bowser plugin version: [e.g. 1.0.0]1.4.0
 - Is KCPS registed: [e.g. No]Yes
 - Game account level: [e.g. 120]120

**Additional context**

**Comment by KanaHayama** [comment]
我这里无法复现问题。
请停留在这一页，然后用“数据工具”-“模板”里试试以下几个模板能不能正常匹配：
+ Factory_Construction_Regular_Digit0
+ Factory_Construction_Regular_Digit3
正常应该是图每个数字都能找得出来的。

另外，请不要在公开场合的截图中露出游戏中的任何ID，这可能让你遭到不合理的人身攻击。
如果你需要我删除这个issue，请在下方留言。

**Comment by QPass** [comment]
用数据工具试了一下，JPEG质量设成80%和100%，结果相同，“0”匹配出8个，“3”匹配出4个。
之后打开脚本发现100%也能正常建造了😓
