### ISSUE TITLE
多次尝试点击母港上的按钮后页面未跳转

### ISSUE THREAD

**Issue by Zhuager** [KanaHayama/KanCollePlayerSimulator#38]
**Version**
1.4.0.3

**Describe the bug**
关联执行单元执行发出远征时出现了错误:
多次尝试点击母港上的按钮后页面未跳转

**Frequency of the bug**
经常

**Comment by KanaHayama** [comment]
是否开启了poi插件上的window API功能？

**Comment by Zhuager** [comment]
没有开启

**Comment by KanaHayama** [comment]
电脑上是否物理地连接了鼠标？

**Comment by KanaHayama** [comment]
报错前的多次尝试点击过程中，有没有出现按钮瞬间高亮但没有被实际点击的现象？

**Comment by Zhuager** [comment]
电脑是笔记本，连接鼠标，使用远程控制。
没有注意到按钮是否出现高亮，这两天出现了好多次，现在正在执行脚本等错误重新出现

**Comment by KanaHayama** [comment]
这是这个版本新加入的重试功能，点击五次还未成功后会报这个错误。目前我在自己电脑上使用从未出现过这个报错。
可能是远程控制可能对此造成了影响。不过还是需要确认一下出现问题时，按钮是否高亮，以及计算机是否息屏，远程控制是否连接正常。

**Comment by Zhuager** [comment]
好的，目前出现情况时远程控制一切正常，电脑也没有息屏，现在等再次出现问题查看按钮状态。

**Comment by Zhuager** [comment]
问题再次出现，出现问题时按钮未高亮
![批注 2020-05-24 232755](https://user-images.githubusercontent.com/15233496/82756649-6ccc0300-9e16-11ea-9bbe-c30d8e896f92.png)

**Comment by KanaHayama** [comment]
这就奇怪了，这只是在检测到跳转失败后再次点击而已，解决的问题是那种按钮会闪一下但点击不成功的状况。所以你那按钮不闪，说明遇到的不是这个改进能解决的状况。那么照理来说你使用之前的版本就会经常遇到点击失败，然后反复超时重试，软件不能正常使用才对。

你用之前的版本时经常点击失败吗？
再遇到这个问题时，不去动游戏自身，而是使用KCPS关于页面的远程控制窗口，打开鼠标控制，看看点那里面的按钮是否游戏中会有对应的反应吧。

**Comment by Zhuager** [comment]
这么一说我用之前的版本的确存在卡在母港界面一直不能出击的情况，需要手动点一下出击按钮然后程序才会进行后续的出击或者远征操作。可能之前没有这个反复尝试多次失败就禁用的功能，所以就一直卡在那里了。

**Comment by Samogrey** [comment]
关联出击或者远征都会出现多次点击母港上按钮失败
点击失败的总控单元会被禁用，但是其他配置里的总控单元会继续正常运行。
未开启win API鼠标模拟，连接了使用无线发射器的无线鼠标，
“报错前的多次尝试点击过程中，有没有出现按钮瞬间高亮但没有被实际点击的现象？”
暂未观测到，之后观测到后报告
计算机未息屏，未合上盖子，屏幕常亮，事后发现时使用远程控制可以正常点击。

**Comment by AL-ZARD** [comment]
我这段时间使用下来，感觉上可能是两个模块在一起触发了发生这种现象

**Comment by AL-ZARD** [comment]
> 我这段时间使用下来，感觉上可能是两个模块在一起触发了发生这种现象

我这是反推的，不是很确定，就是我平时就是早上自动启动三个远征，接任务，5次维修，演习，演习完4次2-2，之后5次2-1，期间设定有每45分钟检测一次收任务，这段期间就很容易出现这个情况，周一的话手动跑35次1-1，和25次2-2的话也很容易出这个情况，但是一天纯在走远征的话就很少出现这个，偶尔出现我怀疑可能和检测收任务撞车了

**Comment by KanaHayama** [comment]
已更新
