### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by start1223** [KanaHayama/KanCollePlayerSimulator#39]
1：当前如舰船编成/装备改装，如果是读取当前游戏配置（常见的使用方式）会使用模板。
但模板内的部分默认选项不太符合个人使用习惯，如默认”允许装备摘取“，但个人偏好为默认“不允许”。

能否通过某个方式，或者提供相应设置来更改默认设定？不然每次N条船N个装备每次都要更改这个有点累。

2：能否允许用户锁定舰船/装备更换的标签页？比如只有BB/CA阵容出击，让玩家在舰船编成里可以只使用BB/CA的标签页。现在的自动计算相对比较慢，还有页数太多翻页也是问题。不确定这样能不能提高效率。

**Comment by KanaHayama** [comment]
1.确实不允许是比较合适的选项，当初从不允许改为允许是因为个别人只有一个某装备且已经放在别的船上时，使用默认的“不允许”导致换不上会找我报错。为了适用性才改成那样，从那之后我就也在考虑是否需要加入默认设置自定义的能力。既然有人提出来了，那我下个版本会开发这个功能。
2.不能假定所有用户都能遵守设定了这种锁定选项就去不使用其他种类舰船，出了问题不会把问题归咎为软件bug。你可以把自动切换标签和自动切换排序的选项关掉，换页速度会变快。

**Comment by start1223** [comment]
第一个反馈非常感谢！
第二个的话，现在我的选项是关闭的，是想进一步提升速度。
不知道能不能考虑这样的实现方式：在编成模块里提供舰种标签页的复选框，默认全部选中，不想使用哪个舰种标签页就去掉，然后会先判定标签页选取后再进行选船计算？

**Comment by KanaHayama** [comment]
使用到那种舰船种类是编成的设定项决定的，再加一个额外的舰船种类限制会导致和前面的种类冲突。不仅导致了一致性问题，还增加了用户的心智负担，明显不是一个好的设计。

**Comment by KanaHayama** [comment]
具体来说，你的提议先设定允许使用的舰船种类，再根据这个种类过滤编成设定项中的舰船。
虽然可以通过单独添加一个全编成配置有效的过滤器功能，加入这类全局过滤能力。
我觉得这个方案不够优雅，引入了更多的功能间耦合，不像现在的设置项能独立控制自己是否被过滤掉这样直观。
最主要的是我认为带来的的性能提升的效益远低于易用性降低的损失。

**Comment by start1223** [comment]
收到，感谢解答。
这个”使用到那种舰船种类是编成的设定项决定的/设置项能独立控制自己是否被过滤掉“的相关功能是否就是指编成模块中，选取类型的“附加脚本函数”？如果是的话那原因是因为我不是进阶型用户，没有（不会！）用过这个高级功能，平时我们这些普通用户会直接使用生成的舰船ID。如果不是的话我没有找到在哪里？

稍微说两句题外话，仅供探讨：如果现有功能是我猜的这个功能的话，从用户使用角度来看，增加额外的入口不会增加用户的心智负担。基于82原则来看的话进阶功能一般只有少量用户使用，大部分用户会需求基于用户直觉的简易功能。至于一致性问题，商用产品会从此原则出发进行必要的联动设计。

举个例子，如果在AB两个场景下均有C功能的使用需求，则两个场景可能均会提供相应入口，或在需求更强的场景下提供直达跳转及文本说明，以及快捷返回这样的模式。这是因为商用产品的特性是功能繁多，用户不会去进行探索，大部分依赖于1-3周的使用培训。这种时候基于用户直觉进行设计反而是大幅度降低用户使用成本的。

至于从开发角度去看待解耦这件事，我不是专业的就不多说了，不过一般也会跟开发商讨折中的实现方式。

**Comment by KanaHayama** [comment]
我的意思是舰船种类是舰船固有的属性，在你填了船的id时就确定了。
我还是觉得用户为整个舰队单独再手动设置一次6艘船舰船种类的交集是多此一举。（不过这么一说，这个信息可以自动得到，不需要用户设置）
而且同时运行多个配置的话，这些配置之间的设置不同，也会在运行时来回改这个过滤器。我不觉得会给性能带来什么好处。
倒是可以再加一个选项，为利用这个过滤器的搜索剪枝，比如只允许加入种类，而不允许除了全部取消外的减少。

**Comment by start1223** [comment]
嗯，这是个人的想法，肯定是不完善的，也可能有理解错误的地方：

人工操作的时候，通常是倾向于最快速选择自己要的船只。这样下来最常用的人工方式就是：先根据目的的不同通常是使用类型切换，如等级从高到低或者是受损程度等等，然后选中单个舰种过滤项（如只有BB），这样只需要在1-5页内就可以快速找到自己所需的船只·，然后循环若干次直到编成完毕。这是由于玩家其实对各种类型的排列结果有自己的预期。

KCPS的工作方式则是选中所有舰种过滤项，然后基于用户当前选中的那个类型进行运算（我打开CONFIG里的两个开关观察过，好像没有什么变化？但运算时间却增加了）。对KCPS来说这些选项不是很有所谓，只要能根据这个对应到舰船ID即可（但舰船ID恰好是游戏没有呈现的一种内部逻辑，因此就会出现和人工操作有比较大的差异的现象）。

我的出发点是提供一个允许用户根据自己对目标的理解（比如倾向5-2练级可能会选较多带V船，那么设置为航母过滤+等级排序，倾向其它目的亦然）进一步模拟人工操作的方式，从而适当节省一些操作步骤所用的时间，以及更贴近人工操作。

这个都是从使用角度去谈的理解，可能对性能确实不会有什么提升。不知道基于这个使用角度来看的话有没有一些具有可行性的解决方案？
