### ISSUE TITLE
卡在罗盘界面，未弹出任何错误窗口

### ISSUE THREAD

**Issue by Samogrey** [KanaHayama/KanCollePlayerSimulator#40]
**Version**
1.4.0.3

**Describe the bug**
出击后卡在某次罗盘界面，并无任何弹窗报错

**Frequency of the bug**
偶发，当前版本仅观测到这一次

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete all of the following information):**
 - OS: Windows
 - OS version: Win10 Pro, 1903
 - OS language: Simplified Chinese
 - Browser: Poi
 - Browser version: 10.5.1
 - KCPS bowser plugin version: 1.4.0
 - Is KCPS registed: Yes
 - Game account level: 120

**Additional context**

**Comment by KanaHayama** [comment]
请问是卡在哪个海域的？

**Comment by KanaHayama** [comment]
我是昨天在6图（中部海域）遇到过一次，后来觉得这问题可能和海域相关，但忘了当时是卡在哪个图了。

**Comment by Samogrey** [comment]
> 我是昨天在6图（中部海域）遇到过一次，后来觉得这问题可能和海域相关，但忘了当时是卡在哪个图了。

7-1（南西海域）做任务时遇到的

**Comment by KanaHayama** [comment]
请问使用近期的版本有没有再遇到过这个问题？

**Comment by Samogrey** [comment]
> 请问使用近期的版本有没有再遇到过这个问题？

1.4.3.0版本暂时没发现此问题
