### ISSUE TITLE
POI更新10.6之后好像就没办法工作了？

### ISSUE THREAD

**Issue by yubanmeixiao** [KanaHayama/KanCollePlayerSimulator#41]
如题，poi更新到10.6之后，发远征都会卡在远征选择界面，不好使了

**Comment by KanaHayama** [comment]
我这里更新后，程序工作正常。

请告诉我你插件上是否选择了“Win API”这个选项。
请用关于页面的“远征控制窗口”检查一下脚本截图功能和鼠标控制功能是否正常。

**Comment by yubanmeixiao** [comment]
WIN API是什么？

**Comment by KanaHayama** [comment]
就是插件上那个写着Windows API的选项啊

**Comment by yubanmeixiao** [comment]
啊，我没有勾选那个使用WINAPI，是这个原因吗？我勾选试试

**Comment by KanaHayama** [comment]
不，你不应该勾。
好了，那么做下一步，用远程控制窗口试试操作游戏。

**Comment by yubanmeixiao** [comment]
稍等一下，我正在做南西，等这次出击结束

**Comment by yubanmeixiao** [comment]
我现在是10.5版本，请等我更新到10.6再测试远程控制窗口

**Comment by yubanmeixiao** [comment]
另外我KCPS终端上，JPEG质量选择的是80，是否是这个原因导致的？

**Comment by KanaHayama** [comment]
我待会试试80%，我自己用的是40%

**Comment by yubanmeixiao** [comment]
我打开10.6之后发现KCPS终端插件有更新……我昨天用10.6的时候还没有更新提示，所以我就直接退回10.5了……0x0

**Comment by KanaHayama** [comment]
我昨天poi发布后更新的，但这个更新应该和你遇到的问题无关，是和那个Win api相关的。

**Comment by yubanmeixiao** [comment]
我刚才试了试远程控制，点了鼠标操作之后可以远程操作
现在远征还有4分钟回来，请稍等我再看看情况

**Comment by yubanmeixiao** [comment]
尝试了一下出击2-1，能正常出击

**Comment by yubanmeixiao** [comment]
然后卡在了选择阵形的页面

**Comment by yubanmeixiao** [comment]
用远程控制窗口，鼠标操作可以选阵营，但是脚本好像无法选，奇怪

**Comment by KanaHayama** [comment]
哦，那帮我测一下是不是那个JPEG质量的原因吧，我正在给KCPS加功能，目前用不了

**Comment by yubanmeixiao** [comment]
好的，等这次出击我把jpeg调整到40再试试

**Comment by yubanmeixiao** [comment]
现在是出击、进击都可以正常选择，入夜是否也可以选择，但是就是会卡在选阵形

**Comment by yubanmeixiao** [comment]
jpeg到40，依旧卡在远征列表那里

**Comment by KanaHayama** [comment]
那就得用数据工具看一下模板能不能匹配上了

**Comment by yubanmeixiao** [comment]
jpeg拉到100也一样卡住，模板匹配是OPENCV，我换成CUDA和自动也一样不行，

**Comment by KanaHayama** [comment]
对了，我看到有人说这个是poi显示分辨率的问题。检查一下你那里poi是否是一点不差的长宽比5:3

**Comment by KanaHayama** [comment]
比如试试分辨率100%，而不是67%

**Comment by yubanmeixiao** [comment]
我现在是分辨率100，但是是1199X720

**Comment by yubanmeixiao** [comment]
我poi一直是100，只不过一直都是1199X720，我现在换成1200X720试试

**Comment by yubanmeixiao** [comment]
好像不能调整1200x720，它会自动换成1199，难顶……

**Comment by yubanmeixiao** [comment]
绝了，我换成67%反而能跑了

**Comment by yubanmeixiao** [comment]
我把分辨率从100%调整到67，然后就好使了……这可咋整

**Comment by yubanmeixiao** [comment]
67调回100之后，又不能用了……哇，但是67的画面真的好小，看着眼睛疼

**Comment by KanaHayama** [comment]
这显然是poi的锅了

**Comment by yubanmeixiao** [comment]
那现在怎么办，是等你更新适配poi的新版本，还是退回10.5，还是只能继续67%？
另外KCPS终端的缩放要根据游戏分辨率进行调整吗？我没看懂说明里的缩放的数值有什么意义

**Comment by KanaHayama** [comment]
因为我不知道我能不能通过改插件的方法适配，所以现在两种选择你自己选一种吧。我之后再看看具体是咋回事

**Comment by yubanmeixiao** [comment]
我好像找到原因了，在poi的显示设置里，有一个poi本身面板的缩放，我之前把poi本身的面板缩放调整到超过100%，我现在拉回到100%就可以用了

**Comment by yubanmeixiao** [comment]
但是奇怪的是，poi本身的面板缩放好像并不会影响游戏画面的大小

**Comment by KanaHayama** [comment]
好，谢谢提供这些有意义的信息，我把手头的功能改完就去试一试。

**Comment by yubanmeixiao** [comment]
我之前缩放是115%，就会卡在远征出击界面，之前拉回100之后，远征立刻就好了——这里指的是分辨率100，而不是之前的67

**Comment by yubanmeixiao** [comment]
这个问题暂时请别关闭，等这次远征回来之后，我重新拉一下那个缩放，再次验证一下这个问题，然后再给你进一步的信息

**Comment by KanaHayama** [comment]
嗯

**Comment by yubanmeixiao** [comment]
我现在是2个屏幕，主屏是3440X1440，副屏是1920X1080

**Comment by yubanmeixiao** [comment]
我在2个屏幕上分别试试各种poi缩放下的应用情况，请稍等，稍后汇总汇报

**Comment by yubanmeixiao** [comment]
主屏情况：
主屏：3440X1440
poi缩放为115%时，画面缩放为100%，1199X720
不知道为什么只要poi缩放达到115就会压缩画面1像素
【卡在远征列表处】
poi缩放为110%时，画面缩放为100%，1200X720
【正常运作】
poi缩放为105%时，画面缩放为100%，1200X720
【正常运作】
poi缩放为100%时，画面缩放为100%，1200X720
【正常运作】

副屏情况：
副屏：1920X1080
poi缩放为115%时，画面缩放为100%，1199X720
不知道为什么只要poi缩放达到115就会压缩画面1像素
【卡在远征列表处】
poi缩放为110%时，画面缩放为100%，1200X720（从这个缩放开始就不会压缩游戏画面（
【正常运作】
poi缩放为105%时，画面缩放为100%，1200X720
【正常运作】
poi缩放为100%时，画面缩放为100%，1200X720
【正常运作】

**Comment by yubanmeixiao** [comment]
目前看来原因就是poi的面板缩放问题了，但是在10.6更新之前（截止到10.5.1），我一直开启的是poi本身的115%缩放，也就是1199X720，都可以很正常的运行，但是在更新10.6之后就出了问题，那1像素就无法识别出来了

**Comment by KanaHayama** [comment]
我找到了问题的原因。
poi的那个缩放UI的功能，在某些缩放大小后，可能是因为舍入误差，导致计算的高度偏小，进而导致下方的像素被裁减掉，然后再被拉伸到正常的显示大小。仔细放大看可以看到此时图像相比100%时变糊了。这样导致图像越靠下形变越大，靠下部的模板都会因为图像错位而无法正常判断。
我记得这个问题之前出现过一次……我这里解决不了……不用缩放或找个好用的缩放值应该是个可以接受的解决方案。
