### ISSUE TITLE
基础入渠”报错，已自动禁用

### ISSUE THREAD

**Issue by lee76827** [KanaHayama/KanCollePlayerSimulator#43]
勾选使用高速修復
出現了這樣的訊息
![1591873016775](https://user-images.githubusercontent.com/63027621/84377590-6ced4080-ac15-11ea-8c62-efb2555f9049.jpg)

重新开机或是删掉重载都没有解决

**Comment by sekurodesu** [comment]
同上，我也是一样的报错

**Comment by KanaHayama** [comment]
@sekurodesu @lee76827 我试了一下，没有遇到诶。
请问你们账号里有未解锁的修复渠吗？
报错是游戏界面在母港界时报的，还是在入渠时报的？
游戏账号中是否有高速修复？

**Comment by sekurodesu** [comment]
我修复渠都解锁了，报错是在下图这个界面报的，游戏账号里是有高速修复的
![捕获](https://user-images.githubusercontent.com/51750095/84399844-4bec1600-ac3c-11ea-9e16-6fa082b299b8.PNG)

**Comment by lee76827** [comment]
同上
也是在选择入渠画面报错
都玩了5年多，怎可能还会没有高速修复呢

**Comment by KanaHayama** [comment]
@sekurodesu @lee76827 
点击“关于”-“调试”-“清空API缓存”后再试呢？

**Comment by sekurodesu** [comment]
刚刚点了试了，还是一样会报错

**Comment by KanaHayama** [comment]
@sekurodesu @lee76827 
请帮忙排查一下。
用数据工具，到“数据”选项卡，点左边的“Resources”看看能不能在右边显示返回的各项资源数量，如果能的话，双击显示出来的"Root"，看看有没有第6项以及第6项有没有正确显示高速修复的数量。

**Comment by KanaHayama** [comment]
![image](https://user-images.githubusercontent.com/15655296/84404911-47801880-abbc-11ea-8d2b-f6e54d5ca982.png)
大概弄完后长这样，显示出来的是个Json数组，而不是Json对象。

**Comment by sekurodesu** [comment]
试了试，只有4项数据哎
![捕获](https://user-images.githubusercontent.com/51750095/84405739-84432280-ac43-11ea-8728-751fb7a5c77f.PNG)

**Comment by KanaHayama** [comment]
诶，莫非你用的是74eo？是的话，我得去看看怎么改74的插件了

**Comment by sekurodesu** [comment]
...........确实是74eo，是老插件获取不到修复桶的数据了是吗？

**Comment by KanaHayama** [comment]
啊，我还以为74eo的插件这里返回的是和poi一样的数据，这次用到了这一项的高速修复，以前没用到，所以就直接拿来用了。我看看能不能去改改看74eo的插件吧。
不过我没用过74eo，上次试了一次，怎么调都失败，像是74EO用到的一个网络库总是报错端口冲突，而且冲突的端口是它要监听的端口，看起来莫名其妙的，我看实在没办法解决，当时就放弃了。
要不你暂时KCPS退回旧版，或者暂时换poi用吧，我感觉我解决这个问题还要费点精力。

**Comment by sekurodesu** [comment]
好吧，先退回1.4.0版，等奏大你的好消息了

**Comment by KanaHayama** [comment]
不，应该退回1.4.0.3

**Comment by KanaHayama** [comment]
我想到了个法子，就是当发现返回的数据只有4项的时候，就直接用其他方法查找高速修复的数量（可能会不准确，但这东西基本不会用空，有点误差应该可以接受）

另外 @ @sekurodesu ，你那里数据工具背景色为什么会是绿色的呀？莫非KCPS本体你用着也是绿色的？
如果你什么都没改过它就是绿色的，那可能这是个bug，我需要复现然后修一下。

**Comment by sekurodesu** [comment]
那就麻烦奏大新版本更新一下这种解决方法了，我那个背景是因为开了护眼模式的，KCPS程序是没问题的

**Comment by KanaHayama** [comment]
为了这个再更个版本，估计又要有人向我抱怨刚下载完就更新了。让我再等两天看看还有没有其他要改进的地方吧。

**Comment by sekurodesu** [comment]
好的，辛苦奏大了

**Comment by KanaHayama** [comment]
麻烦看一下是否已经解决

**Comment by sekurodesu** [comment]
试了试，已解决，感谢奏大
