### ISSUE TITLE
下载范例配置之后无法在KCPS中打开

### ISSUE THREAD

**Issue by zhang2wk** [KanaHayama/KanCollePlayerSimulator#46]
之前买了KCPS一直只用来收放远征，直到最近才想自己学着设计出击配置。结果发现下载了范例配置的json之后用kcps打开弹窗说：

‘’ unexpected character encountered while parsing value: <. Path '', line 0, position 0. ''
请问奏大这个应该怎么解决呢？

**Comment by KanaHayama** [comment]
可能是下载的文件不完整或者有错误吧？

**Comment by zhang2wk** [comment]
> 可能是下载的文件不完整或者有错误吧？

的确是文件不完整，我感觉自己就像一个憨批...
