### ISSUE TITLE
关于陆航的建议

### ISSUE THREAD

**Issue by yubanmeixiao** [KanaHayama/KanCollePlayerSimulator#48]
就是有的时候想挂着捞船（活动图）
但是因为陆航连续出击就容易红脸，有的时候就算主队等待了近十分钟，陆航也依旧是红脸。
请问有办法设置一个在每次出击完之后，都把陆航翻到休息，然后等到陆航疲劳结束再正式出击，重新把陆航翻到出击（这个在单次出击里面自带）的功能吗？

**Comment by KanaHayama** [comment]
已经有一个整备陆航执行单元设计用来做这个，它可以插入到出击后的步骤中。
但好像实际用起来好不好用我还没有进一步确认，因为我还没开始打这次活动。
等我测试没问题或者修复问题后我会关闭这个issue。

**Comment by yubanmeixiao** [comment]
好吧，活动只有半个月了，再不打可能来不及了……还是说准备吃丁？

**Comment by KanaHayama** [comment]
肯定要全甲啊，今天就开始打

**Comment by yubanmeixiao** [comment]
为什么我听出了鸽子的味道？咕咕咕，已经进场了咕咕咕……

**Comment by KanaHayama** [comment]
前19个甲章都有了，第20个肯定要拿的。
推图刷闪全可以自动，7*24小时不间断，剩两星期完全来得及。

**Comment by KanaHayama** [comment]
已确认出击后整备陆航执行单元不能正确休息的原因出在poi插件处，已发布插件的更新。
在“关联出击”的出击后的任意步骤关联整备陆航执行单元即可在出击后休息，但要注意该步骤收到事件数量不可以算上整备陆航执行单元。
