### ISSUE TITLE
使用52脚本时无法自动选择阵型

### ISSUE THREAD

**Issue by Hakurm** [KanaHayama/KanCollePlayerSimulator#49]
版本号 1.4.1.3
POI版本 10.6.0
Os Ver  Windows10-64bit
使用52出击脚本时无法自动选择阵型，其余功能正常。能进海域，能点罗盘，但是一到选阵型的时候没反应，手动选完以后正常撤退回港再出击。

**Comment by KanaHayama** [comment]
去这个5-2海域卡住的选阵型界面，打开数据工具，转到“模板”选项卡，选择“Sortie_Formation”，点匹配。
正常来说此时会在下方文本框显示匹配的信息，不成功就说明你电脑的默认字体改过了。

**Comment by Hakurm** [comment]
![image](https://user-images.githubusercontent.com/69738011/90341964-3bf10980-dfd2-11ea-8043-81e9bb776d81.png)
恢复默认字体后好像能匹配到 但是还是没有解决问题

**Comment by KanaHayama** [comment]
能匹配到就能正常工作。
我不清楚你说的没有解决问题是指什么。

**Comment by Hakurm** [comment]
啊 我把程序删了重新解压了一下就好了 谢谢
