### ISSUE TITLE
勾选启用时显示“无法定位当前页面，导航失败”

### ISSUE THREAD

**Issue by TaihouKai** [KanaHayama/KanCollePlayerSimulator#5]
**Version**
1.1.0.1

**Describe the bug**
勾选启用时显示“无法定位当前页面，导航失败”

**Frequency of the bug**
总是

**To Reproduce**
1. 在浏览器和插件两端都设置好端口和口令
2. 点击启用，报错

**Expected behavior**
应该能捕捉到的，难道是硬件加速的原因吗……

**Screenshots**
就是单纯的一行报错，不需要截图了吧

**Environment (please complete all of the following information):**
 - OS: Win10
 - OS version: 版本1803 OS内部版本17134.285
 - OS language: 简体中文
 - Browser: Poi
 - Browser version: 9.0.1
 - KCPS bowser plugin version: 1.0.1
 - Is KCPS registed: No
 - Game account level: 108

**Additional context**
硬件加速**未**禁用

**Comment by KanaHayama** [comment]
那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。

**Comment by KanaHayama** [comment]
看能不能捕捉到画面很简单，http://localhost:5277/capture。插件仓库的readme写过的东西。
另外，新版本不会受硬件加速的影响，发布前微博上提到过了。

**Comment by TaihouKai** [comment]
> 那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。

您好，感谢回复，我根据您说的试了下
![s0k3n1t0qch_3dcw ncnm a](https://user-images.githubusercontent.com/19760299/45588967-987db280-b8eb-11e8-8324-93c32405527d.png)

状态信息如图，停留在“等待完全返回母港”就不动了

**Comment by KanaHayama** [comment]
> > 那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。
> 
> 您好，感谢回复，我根据您说的试了下
> ![s0k3n1t0qch_3dcw ncnm a](https://user-images.githubusercontent.com/19760299/45588986-bfd47f80-b8eb-11e8-896a-ce578232a89a.png)
> 
> 状态信息如图，停留在“等待完全返回母港”就不动了

那先照着上面的方法测试能不能正常获取图像。

**Comment by TaihouKai** [comment]
> > > 那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。
> > 
> > 
> > 您好，感谢回复，我根据您说的试了下
> > ![s0k3n1t0qch_3dcw ncnm a](https://user-images.githubusercontent.com/19760299/45588986-bfd47f80-b8eb-11e8-896a-ce578232a89a.png)
> > 状态信息如图，停留在“等待完全返回母港”就不动了
> 
> 那先照着上面的方法测试能不能正常获取图像。

您好，我按照以下步骤操作的：

1. 先正常进入游戏
![o65cau on12dc2 w8jxbhli](https://user-images.githubusercontent.com/19760299/45592079-dd2c3c80-b931-11e8-8ec5-af56d14f8a05.png)

2. 在地址栏输入http://localhost:5277/capture
![w 7iez v pkt xv vdu 2q](https://user-images.githubusercontent.com/19760299/45592082-faf9a180-b931-11e8-9055-43b1dfc4dd44.png)
之后就是黑屏了

**Comment by KanaHayama** [comment]
> > > 那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。
> > 
> > 
> > 您好，感谢回复，我根据您说的试了下
> > ![s0k3n1t0qch_3dcw ncnm a](https://user-images.githubusercontent.com/19760299/45588986-bfd47f80-b8eb-11e8-896a-ce578232a89a.png)
> > 状态信息如图，停留在“等待完全返回母港”就不动了
> 
> 那先照着上面的方法测试能不能正常获取图像。

用网页浏览器，端口用自己的设置

**Comment by TaihouKai** [comment]
> > > > 那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。
> > > 
> > > 
> > > 您好，感谢回复，我根据您说的试了下
> > > ![s0k3n1t0qch_3dcw ncnm a](https://user-images.githubusercontent.com/19760299/45588986-bfd47f80-b8eb-11e8-896a-ce578232a89a.png)
> > > 状态信息如图，停留在“等待完全返回母港”就不动了
> > 
> > 
> > 那先照着上面的方法测试能不能正常获取图像。
> 
> 用网页浏览器，端口用自己的设置

呃……我先研究下载怎么把插件弄到chrome里

**Comment by KanaHayama** [comment]
> > > > > 那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。
> > > > 
> > > > 
> > > > 您好，感谢回复，我根据您说的试了下
> > > > ![s0k3n1t0qch_3dcw ncnm a](https://user-images.githubusercontent.com/19760299/45588986-bfd47f80-b8eb-11e8-896a-ce578232a89a.png)
> > > > 状态信息如图，停留在“等待完全返回母港”就不动了
> > > 
> > > 
> > > 那先照着上面的方法测试能不能正常获取图像。
> > 
> > 
> > 用网页浏览器，端口用自己的设置
> 
> 呃……我先研究下怎么把插件弄到chrome里

啊？就把http://localhost:5277/capture复制到浏览器地址栏然后按回车有那么难吗？

**Comment by TaihouKai** [comment]
> > > > > > 那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。
> > > > > 
> > > > > 
> > > > > 您好，感谢回复，我根据您说的试了下
> > > > > ![s0k3n1t0qch_3dcw ncnm a](https://user-images.githubusercontent.com/19760299/45588986-bfd47f80-b8eb-11e8-896a-ce578232a89a.png)
> > > > > 状态信息如图，停留在“等待完全返回母港”就不动了
> > > > 
> > > > 
> > > > 那先照着上面的方法测试能不能正常获取图像。
> > > 
> > > 
> > > 用网页浏览器，端口用自己的设置
> > 
> > 
> > 呃……我先研究下怎么把插件弄到chrome里
> 
> 啊？就把[http://localhost:5277/capture复制到浏览器地址栏然后按回车有那么难吗？](http://localhost:5277/capture%E5%A4%8D%E5%88%B6%E5%88%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%9C%B0%E5%9D%80%E6%A0%8F%E7%84%B6%E5%90%8E%E6%8C%89%E5%9B%9E%E8%BD%A6%E6%9C%89%E9%82%A3%E4%B9%88%E9%9A%BE%E5%90%97%EF%BC%9F)

啊……所以我在chrome里输入了上述网址以后是这样的
![yk5e y4 cfw b 9qu6 d9](https://user-images.githubusercontent.com/19760299/45592688-6f3c4100-b942-11e8-8060-1770ac4c89ed.png)

**Comment by KanaHayama** [comment]
> > > > > > > 那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。
> > > > > > 
> > > > > > 
> > > > > > 您好，感谢回复，我根据您说的试了下
> > > > > > ![s0k3n1t0qch_3dcw ncnm a](https://user-images.githubusercontent.com/19760299/45588986-bfd47f80-b8eb-11e8-896a-ce578232a89a.png)
> > > > > > 状态信息如图，停留在“等待完全返回母港”就不动了
> > > > > 
> > > > > 
> > > > > 那先照着上面的方法测试能不能正常获取图像。
> > > > 
> > > > 
> > > > 用网页浏览器，端口用自己的设置
> > > 
> > > 
> > > 呃……我先研究下怎么把插件弄到chrome里
> > 
> > 
> > 啊？就把[http://localhost:5277/capture复制到浏览器地址栏然后按回车有那么难吗？](http://localhost:5277/capture%E5%A4%8D%E5%88%B6%E5%88%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%9C%B0%E5%9D%80%E6%A0%8F%E7%84%B6%E5%90%8E%E6%8C%89%E5%9B%9E%E8%BD%A6%E6%9C%89%E9%82%A3%E4%B9%88%E9%9A%BE%E5%90%97%EF%BC%9F)
> 
> 啊……所以我在chrome里输入了上述网址以后是这样的
> ![yk5e y4 cfw b 9qu6 d9](https://user-images.githubusercontent.com/19760299/45592688-6f3c4100-b942-11e8-8060-1770ac4c89ed.png)
> 
> 我原来以为要把插件移到chrome里这才会生效……

那你就想办法让插件好用吧。好用的时候这里会显示截图。

**Comment by TaihouKai** [comment]
> > > > > > > > 那就把动作前等待返回母港打开。它会等你返回母港后再开始识别当前页面在哪。这个选项默认关闭。
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，感谢回复，我根据您说的试了下
> > > > > > > ![s0k3n1t0qch_3dcw ncnm a](https://user-images.githubusercontent.com/19760299/45588986-bfd47f80-b8eb-11e8-896a-ce578232a89a.png)
> > > > > > > 状态信息如图，停留在“等待完全返回母港”就不动了
> > > > > > 
> > > > > > 
> > > > > > 那先照着上面的方法测试能不能正常获取图像。
> > > > > 
> > > > > 
> > > > > 用网页浏览器，端口用自己的设置
> > > > 
> > > > 
> > > > 呃……我先研究下怎么把插件弄到chrome里
> > > 
> > > 
> > > 啊？就把[http://localhost:5277/capture复制到浏览器地址栏然后按回车有那么难吗？](http://localhost:5277/capture%E5%A4%8D%E5%88%B6%E5%88%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%9C%B0%E5%9D%80%E6%A0%8F%E7%84%B6%E5%90%8E%E6%8C%89%E5%9B%9E%E8%BD%A6%E6%9C%89%E9%82%A3%E4%B9%88%E9%9A%BE%E5%90%97%EF%BC%9F)
> > 
> > 
> > 啊……所以我在chrome里输入了上述网址以后是这样的
> > ![yk5e y4 cfw b 9qu6 d9](https://user-images.githubusercontent.com/19760299/45592688-6f3c4100-b942-11e8-8060-1770ac4c89ed.png)
> > 我原来以为要把插件移到chrome里这才会生效……
> 
> 那你就想办法让插件好用吧。好用的时候这里会显示截图。

嗯……我原先有口令，现在把口令去掉了可以截图

**Comment by TaihouKai** [comment]
更新：把分辨率改成固定值之后已解决
