### ISSUE TITLE
1.4.2更新后基础编成单元舰队数据导入的问题

### ISSUE THREAD

**Issue by AC-Link** [KanaHayama/KanCollePlayerSimulator#50]
在取消了csv导入后，现在并不清楚应该用哪种方式导入已经配置好的舰队编号，又回到了手动输入的状态，请问如何才选择配置csv文件后自动导入数据呢？还是说需要使用付费版模板才能导入数据呢？

**Comment by KanaHayama** [comment]
哦，没错的，现在确实都是用载入配置功能载入舰船。以前编成功能很简易，直接存取id就行了，现在id基本不怎么用了，都是附加脚本配合后面的选项自动选船，所以这功能没用了。我记得上个版本的时候这功能就因为编成执行单元大改而有人报告说无法正常工作了。
