### ISSUE TITLE
实在是解决不了，只能麻烦奏大了

### ISSUE THREAD

**Issue by kcpsreport** [KanaHayama/KanCollePlayerSimulator#52]
奏大好：
实在是不会用python，想请教下这两个问题有没有别的办法解决，如果没有能不能提下需求？

第一个是当前使用多个独占模式的配置进行循环的时候，没找到怎么设置整个配置的队列内权重。试过把整个配置里所有单元的优先度都调高，但是没用。
然后现状就是比如ABC三个均可以执行的配置，一定会按照A-B-C-A-B-C的顺序去执行，除非因为疲劳或者别的原因进入等待。
这样就会出现两种情况：
1.远征的配置会在当前循环执行完成后再发出，即使已经在母港收回了远征，也会先执行出击的配置。
2.没法按照A-A-A（A进入等待）-B-B（B进入等待）-C这样的顺序去穿插出击。比如5-5和偷油两个配置，5-5当前疲劳满足可以立刻去打第二个循环，但是会被插入一个偷油循环。
所以不知道有没有什么办法能够完整控制整个配置的队列内权重？
期望的目标是当远征配置可以开始循环的时候能挂起别的配置，先把远征发出去；以及能够让权重高的配置连续出击直到进入等待，再进行下一个配置。

第二个问题：
（非全自动配置）刷闪完了一直修理的时候很容易把其它配置正在使用的船也给修了，比如55的4DD。这个看了脚本是可以解决的，但是实在不会python，那段对应有用的部分拷出来应该也不能直接用。能不能增加一个功能只修理该配置编成列表里的船，或者能给一个起到类似作用的python简单脚本吗？最简单的用船只ID来列举”这个修理只修这些船“然后我们照着填的也行。

**Comment by KanaHayama** [comment]
对于第一个问题，独占模式设计上就是FIFO队列，谁先排队谁先执行。该队列没有优先级的区别（之后可能会有优先级，让远征的优先级高一些）。执行单元的优先级控制的也不是这个地方的优先级，你可以完全不用管那个优先级。你可以通过控制出击的循环等待时间来降低某配置的频度。循环等待时间也可以用python脚本控制，但队列不能用脚本控制。

对于第二个问题，编成执行单元和入渠执行单元是独立的执行单元，入渠不可能也不应该知道编成执行单元的信息（它们应当是互相独立并且解耦的），另外编成执行单元的舰船选择是动态的（因为可以用python控制，获得新船或者拆船也会让可能选择的船的范围改变），所以你的这一想法并不现实。你可以用脚本过滤器筛掉你不想入渠的船，这需要编写python脚本。

对于复杂的逻辑，简单的UI操作就是非常的无力，你的需求已经超出了一般使用的范畴，建议花2个小时学一遍Python。

一个范例附加脚本过滤器可以是：
```python
def filter(id):
	return id not in [1, 2, 3, 4]
```
列表里面填的是不想让它修理的船。如果想反过来只让它修列表里的船，把not去掉就行了。

**Comment by kcpsreport** [comment]
明白了，谢谢奏大。

尝试自己对着教程改了改，不知道有没有错，请教一下有没有更好的写法（能更快清晰的，因为这个表我觉得大概一两个月可能就会动一次）？目标就是列出在所有出击舰队中要用的CLDD不被扔去修……
# -*- coding: UTF-8 -*-
def filter(id): 
	use45 = [4, 5, 6] #4-5所用CLDD[4睦月, 5如月, 6天龙]
	use55 = [7, 8] #5-5所用CLDD[7睦月, 8如月]
	use65 = [9] #5-5所用CLDD[9睦月]
	useall = use45 + use55 + use65 #生成总列表
	return id not in uesall

**Comment by KanaHayama** [comment]
返回的是布尔值，不是列表

**Comment by kcpsreport** [comment]
上次的函数试了几天很好用！但是实在不好意思，我又来求助了……我保证这是最后一次问脚本相关问题！
就是我想要在若干个确定ID的船里选取一条船，选取条件是这条船上特定的某一装备槽（不需要包含打孔）带有特定的装备如”大発動艇$“，看了网上的教程整了整完全不行，所以还想请问一下这个脚本应该怎么写……

另外这些用于编成，维修的筛选器要是能写几个模板直接提供下载，对于我们这种不会编程的小白来说会非常有帮助。虽然不会写脚本，但是用编辑器改改ID和条件还是能行……

**Comment by KanaHayama** [comment]
个人定制需求请预约一对一使用教学服务，这实在不是一个我直接写不测试就能写出来不会出错的复杂且不对所有用户有意义的需求。

你需要自己写一个函数，使用到的API大概有
ShipUtility.All()获得所有舰船的对象（列表）
ShipUtility.AllEquipments(shipObj)得到多有该船身上的装备id（列表）
EquipmentConstUtility.EquipmentConst(equipmentId)查询装备对应的常量对象
EquipmentConstUtility.Name(equipmentConstObj)获得装备的名称
然后比较名称是否等于日文原文的大发动艇即可，对于满足要求的船
ShipUtility.Id(shipObj)得到舰船id
然后每次调用返回一个id，可以使用yield return实现每次返回一个不同的值

我建议你在遇到这种偏门的需求时认真考虑一下是否有必要这么做才能满足你的需求，实在没有办法变通时再考虑写脚本。

**Comment by kcpsreport** [comment]
我在旺旺上留言了，但旺旺挺奇怪的，搜索账号出来的是阿里巴巴账号，淘宝的只有代挂……如果你方便的话我现在就可以拍。
________________________________
发件人: Kana <notifications@github.com>
发送时间: 2020年10月11日 0:37
收件人: KanaHayama/KanCollePlayerSimulator <KanCollePlayerSimulator@noreply.github.com>
抄送: kcpsreport <kcpsreport@outlook.com>; Author <author@noreply.github.com>
主题: Re: [KanaHayama/KanCollePlayerSimulator] 实在是解决不了，只能麻烦奏大了 (#52)


个人定制需求请预约一对一使用教学服务，这实在不是一个我直接写不测试就能写出来不会出错的复杂且不对所有用户有意义的需求。

你需要自己写一个函数，使用到的API大概有
ShipUtility.All()获得所有舰船的对象（列表）
ShipUtility.AllEquipments(shipObj)得到多有该船身上的装备id（列表）
EquipmentConstUtility.EquipmentConst(equipmentId)查询装备对应的常量对象
EquipmentConstUtility.Name(equipmentConstObj)获得装备的名称
然后比较名称是否等于日文原文的大发动艇即可，对于满足要求的船
ShipUtility.Id(shipObj)得到舰船id
然后每次调用返回一个id，可以使用yield return实现每次返回一个不同的值

我建议你在遇到这种偏门的需求时认真考虑一下是否有必要这么做才能满足你的需求，实在没有办法变通时再考虑写脚本。

―

**Comment by KanaHayama** [comment]
没有收到任何留言。
强烈建议自行编写脚本。
