### ISSUE TITLE
远征偶尔发错

### ISSUE THREAD

**Issue by kcpsreport** [KanaHayama/KanCollePlayerSimulator#53]
设定的A2和B1远征，在1个月的时间内A2三次被发到8一次被发到A1，B1两次被发到16。

**Comment by KanaHayama** [comment]
虽然听别人说过有偶尔发错远征的情况，但我自己从来没遇到过。

下个版本可能把对应位置的逻辑加强一点，但因为我从来没遇到过，所以到底能不能达到绝对不发错我是没法确定的。

**Comment by kcpsreport** [comment]
我这边是POI缩放100%，分辨率100%。
尝试过调整config里的鼠标点击延迟为（我开始以为是动作太快导致没能成功向下翻页）
PointerFixedDelayMiliseconds: 20,
PointerMoveDelayMilliseconds: 20,
PointerDownDelayMilliseconds: 150,
PointerUpDelayMilliseconds: 150,
但是没有生效。
不知道这个信息能不能作为参考。

**Comment by KanaHayama** [comment]
请问现在是否还有发错的问题？
