### ISSUE TITLE
闪退汇报

### ISSUE THREAD

**Issue by kcpsreport** [KanaHayama/KanCollePlayerSimulator#54]
一下午用某个配置复现了7-8次，也许能帮助定位原因？

首先这是单个配置内的AB两套“关联出击”。AB之间不联动的时候，均可以顺利执行循环到自动停止后禁用除了”关联出击“外的所有执行单元（我的设置），无闪退。

随后设定为A循环自动停止后禁用除了”关联出击“外的所有执行单元，**并触发B配置的”关联出击执行单元“**，通过这个方式进行两套配置的联动，结果开始多次闪退。观察后发现闪退必然发生在A循环出击后的入渠阶段（**这个阶段之后没有其他执行单元，就是循环完成，自动停止并触发B循环的阶段**）。看了log发现有时入渠阶段没有能完整执行完就闪退了（我设定了3个互补的入渠执行单元并要求回报3个事件才进入下一阶段）。

给B循环增加了一个开始前10秒等待，继续闪退。
让A循环自动停止后触发一个“串联（倒计时）”并设定10秒等待，等待完成后触发无等待的B循环，反复试验无闪退。

以上就是全部现象。

**Comment by KanaHayama** [comment]
你可以把这个配置通过邮件发给我，我来确认一下我这里是否能够复现。
之前有用户报告新版本出现闪退问题，但我一直也遇不到。
1.4.2版本有一些改动，这些用户在重新编写配置后再没有遇到闪退，此解决方案之前已经在FAQ上提到过了，如果你的配置是在旧版本上制作的，你也可以尝试一下。

**Comment by kcpsreport** [comment]
这个配置是闪退的配置，大部分确实是在1.4.2.2下面写的，但是有些单元（比如出击）是复用了之前1.3等等版本的存货。我会把这部分也重写一遍的。辛苦奏大了。
________________________________
发件人: Kana <notifications@github.com>
发送时间: 2020年10月11日 0:43
收件人: KanaHayama/KanCollePlayerSimulator <KanCollePlayerSimulator@noreply.github.com>
抄送: kcpsreport <kcpsreport@outlook.com>; Author <author@noreply.github.com>
主题: Re: [KanaHayama/KanCollePlayerSimulator] 闪退汇报 (#54)


你可以把这个配置通过邮件发给我，我来确认一下我这里是否能够复现。
之前有用户报告新版本出现闪退问题，但我一直也遇不到。
1.4.2版本有一些改动，这些用户在重新编写配置后再没有遇到闪退，此解决方案之前已经在FAQ上提到过了，如果你的配置是在旧版本上制作的，你也可以尝试一下。

―

**Comment by KanaHayama** [comment]
你直接回复github的邮件的话我是看不到附件的，因为邮件不是回给我的。
请不要在github上发布你的配置文件，那可能会导致舰船id泄露。
请将配置发送到orzfirst@vip.qq.com。

**Comment by kcpsreport** [comment]
已经发送了。
________________________________
发件人: Kana <notifications@github.com>
发送时间: 2020年10月11日 7:25
收件人: KanaHayama/KanCollePlayerSimulator <KanCollePlayerSimulator@noreply.github.com>
抄送: kcpsreport <kcpsreport@outlook.com>; Author <author@noreply.github.com>
主题: Re: [KanaHayama/KanCollePlayerSimulator] 闪退汇报 (#54)


你直接回复github的邮件的话我是看不到附件的，因为邮件不是回给我的。
请不要在github上发布你的配置文件，那可能会导致舰船id泄露。
请将配置发送到orzfirst@vip.qq.com<mailto:orzfirst@vip.qq.com>。

―

**Comment by KanaHayama** [comment]
我用这个配置，只改了船和装备，跑了10次，一次都没闪退。
其他人有遇到过远征回来后闪退的。
目前完全总结不出问题原因，我怀疑是系统的问题。

**Comment by kcpsreport** [comment]
我的感觉是，可能个别时候判断或者动作太快了导致的冲突？

另外2个没有导致闪退但是也出现了的现象：
类似的远征循环，收了远征应该返回母港的时候，直接报错“没有找到对应的图像（大意）”，这时游戏画面在显示远征收益的那个回收页。我猜测就是还没来得及返回母港，KCPS已经判断为“此时应该在母港界面”，然后对不上，报错了。但是这个现象数百次远征仅出现了一次（配置是1.4.2下面做的），我也没能复现。
另一个是使用编成展开的时候，用默认的CONFIG20/20/50/50，向下翻页的时候甚至给我一种有滚动条的感觉，极快。手动猛点或者长按向下翻页都达不到这个效果。CONFIG改成25/25/175/175接近人手动。

我那个配置同时禁用一堆执行单元顺便启用执行单元，会不会有一定的关联呢？

**Comment by KanaHayama** [comment]
太长了，大致看了一下。
对于你说的没等上个操作结束就判断说找不到页面是因为你没有开启开始动作前等待返回母港。
闪退我复现不了就说明正常执行范围的逻辑没有问题。
闪退这问题出在我更新加壳软件大版本之后，其实很有可能是加壳软件的问题，配合个别系统不兼容导致的。因为照正常逻辑，出现错误肯定会被我兜底的异常捕获语句拦截，不可能直接程序就没了。

**Comment by kcpsreport** [comment]
别的问题明白了。
但是那个远征的我恰好又出了一次，因为我是开了动作前等待返回母港的，就仔细看了一下LOG。

2020-10-17 19:49:06,115 [EventDispatcher] INFO  KancollePlayerSimulatorKai.RelationalExpeditionWorkflow [(null)] - 执行单元"[远征][3]"刷新游戏数据
2020-10-17 19:49:15,424 [SeriesByTimerWorkflowService] INFO  KancollePlayerSimulatorKai.SeriesByTimerWorkflow [(null)] - 串联（倒计时）"[通知][完成]"时间到
2020-10-17 19:49:15,424 [SeriesByTimerWorkflowService] INFO  KancollePlayerSimulatorKaiCore.Task [(null)] - 已取消任务"返回提督室"
2020-10-17 19:49:16,880 [Scheduler] ERROR KancollePlayerSimulatorKaiCore.Scheduler [(null)] - 调度器捕获到异常:
    无法定位当前页面，导航失败
2020-10-17 19:49:16,886 [EventDispatcher] ERROR KancollePlayerSimulatorKaiCore.WorkflowBase [(null)] - “[远]跑桶远征”中的“[控制][远征][3]”报错，已自动禁用：
    执行刷新游戏数据时检查到错误
        无法定位当前页面，导航失败

好像是别的正在运行的执行单元恰好取消了远征的返回母港，导致返回不了报错？
我尝试把关联远征的刷新数据优先级改成100试试。

**Comment by KanaHayama** [comment]
请问新版本1.4.3.1是否还会闪退？

**Comment by kcpsreport** [comment]
1.4.3.2版本，2天使用未发现闪退。
