### ISSUE TITLE
更新了资源上限之后入渠后会提示浏览器插件错误

### ISSUE THREAD

**Issue by sekurodesu** [KanaHayama/KanCollePlayerSimulator#56]
如题，用的是74eo浏览器，在一个出击模块内的入渠结束之后会弹窗报错，然后就卡在入渠界面了，但是如果手动回到母港的话，远征那些还是会自动收的，就是当前执行的出击模块会停住。
并且报错还不止一种
![QQ图片20201122002255](https://user-images.githubusercontent.com/51750095/99880861-57b31e00-2c59-11eb-8321-857de462dd69.png)
![微信图片_20201129164739](https://user-images.githubusercontent.com/51750095/100536248-a61c7a00-3262-11eb-8011-ee9c5b2033b3.png)
![微信图片_20201129164839](https://user-images.githubusercontent.com/51750095/100536283-e8de5200-3262-11eb-8dc1-8f5319cab6b6.png)

**Comment by KanaHayama** [comment]
poi浏览器中无此问题。
KCPS中从没有硬编码过最大资源量，所以此类问题绝对不可能是KCPS的问题。
74EO的插件不是我维护，我也没有能力维护。
这是KCPS本体的仓库，无法解决插件相关问题。
请去对应的仓库提问。谢谢。
