### ISSUE TITLE
关于活动给的新装备脚本查不到

### ISSUE THREAD

**Issue by rippi387** [KanaHayama/KanCollePlayerSimulator#57]
如题目，打通活动拿到新的鱼雷和寒冷地装备&甲板要员，然后发现用自动远征或者其他的脚本时发现换装备出现死循环，用排查装备的脚本排查后发现这几个活动给的新装备查不到，但是我去数据库看了更新日志发现28号的时候就已经有更新装备了，所有不知道怎么回事，我用的全是最新版本的软件和脚本。
第36页：増設バルジ(大型艦) 有 1 个， プリエーゼ式水中防御隔壁 有 2 个， 艦隊司令部施設 有 1 个， 熟練艦載機整備員 有 1 个， 夜間作戦航空要員 有 1 个， 夜間作戦航空要員+熟練甲板員 有 1 个， 91式高射装置 有 3 个
在夜間作戦航空要員+熟練甲板員后面有两个寒冷地装备&甲板要员查不到，鱼雷的也是。

**Comment by KanaHayama** [comment]
脚本自带从github仓库获取最新数据的功能。该功能会在每次启动后或者点击检查更新按钮后执行。
如果你发现数据库已经包含了新装备的数据，而脚本仍不能识别。则说明你的电脑无法连接到githubusercontent.com。
请修复网络连接后更新再试。

**Comment by rippi387** [comment]
已经成功解决，另外我kcps.info突然上不去，他提示wordpress错误，用了其他设备也是同样的情况，科学上网也解决不了，前阵子还可以上得去，谢谢奏大。

**Comment by rippi387** [comment]
已经解决，今天发现kcps.info可以上去了
