### ISSUE TITLE
希望数据工具的「截图」和本体的「选取点击范围」等处支持 PNG

### ISSUE THREAD

**Issue by LoveJudgement** [KanaHayama/KanCollePlayerSimulator#58]
**Is your feature request related to a problem? Please describe.**
目前这些地方都会按 JPG 解码然后报错。

**Describe the solution you'd like**
当浏览器插件的 `/capture` 返回 PNG 的时候这些地方应该能正确解码。
因为当浏览器插件运行在本地 / 局域网的时候使用 JPG 可以说是没有任何优势。用 PNG 反而抠模板的时候比较精确……

**Describe alternatives you've considered**
KCPS 本体在 HTTP Header 里发送 `Accept` 来选择需要的格式……听起来过于 over engineering

**Additional context**

**Comment by KanaHayama** [comment]
这两个功能我没拿来抠过模板，想不出来这俩功能怎么抠模板。所以处理PNG是KCPS完全用不到的功能。
我做模板图片的时候，都是用poi自带的截图功能，或者“辅助工具”里的“延迟截图png”python程序，这些都不涉及到KCPS。
因为完全用不上PNG，所以我不清楚让KCPS支持PNG的意义

**Comment by LoveJudgement** [comment]
可以直接手动访问 `/capture` 拿 PNG 然后直接粘到编辑器里……
这样可以不影响浏览器自身的截图功能（比如 EO 默认是仅保存到文件，不会写剪贴板）。
目前因为 KCPS 选取点击范围拿到 PNG 会直接报错，需要使用相关功能的时候我需要手动去改插件设置让它返回 JPG。

另外讲真我觉得返回 JPG 和 PNG 比没什么优势，反而导致 artifact 从而在对比的时候更容易产生问题。其实我觉得默认应该用 PNG……

**Comment by KanaHayama** [comment]
在有严重失真的时候也能正确匹配正是我当时设计时想要的效果。我反倒是觉得png不适合把插件和本体放到互联网上不同地方的场景。
poi的截图功能也是保存到文件里，保存到剪贴板反而要多一个设置画布分辨率的步骤。我都是截图完直接用ps打开文件再编辑的。你想做模板图片的话，建议你也试试这个方法。

**Comment by LoveJudgement** [comment]
模糊匹配我同意是必要的功能，毕竟存在缩放之类的需求……

但是 JPG 我真觉得不是个好设计……
一个就是上面提到的 artifact。虽然模糊匹配确实是重要需求，然而其实对于很多用户（比如我）来说精确匹配已经足够，甚至还能减少各种发错远征之类的疑难杂症。模板之类的也就随便画个框就行，不用考虑模糊匹配带来的问题。
而与之相对，JPG 带来的优势并不大。即使双方之间带宽极小以至于不得不压缩，PNG 默认的无损压缩应该相当够了……~又不是 BMP~

对于在两端之间需要经过网际网络的 use case……我个人的看法是应该强烈建议用户不要这么做，除非他们真的明白这意味着什么。
除非在插件端能够提供 HTTPS，否则 HTTP 明文传输带来的风险实在是太大了，尤其是插件端存在调用 WinAPI / Electron API 的能力的情况下。~虽然这游戏本身就 HTTP 明文把 token 发来发去~
（EO 版的插件只监听 loopback，相当于强制用户自己设置一个反代，如果他们真的需要这样用。）

**Comment by KanaHayama** [comment]
我依然觉得jpg很符合我的要求。我平时设置的jpg质量才40，发错远征的问题我从来没遇到过。我做模板图片的工作流程并不在意图片格式，反正都是你说的画个框嘛。
改成支持png倒不难，jpeg解码失败时换成用png解码就行了。但我完全想不到应用场景，你要是说传bmp我倒觉得能省掉编解码可能还有点用，png我真没觉得有任何意义，毕竟还是已经有的jpg完全满足需求。你要是坚持解码png这功能有用的话我就放到下次更新里实现一下，无非就解码的地方try-catch一下嘛。

**Comment by LoveJudgement** [comment]
不重点其实是随便画个框然后阈值可以直接写 0……就不用担心奇奇怪怪的问题。

我是觉得 PNG 比起 JPG 是一个更好的解。而且现在只要不使用选取点击范围之类的功能，PNG 也完全 work。所以我平时一直是用 PNG 的。但是活动期间总是要选地图点什么的就得记得改……（而且目前那个地方没 catch 所以会直接 crash 掉整个进程）

**Comment by KanaHayama** [comment]
因为有缩放的问题，填0不适用。我还是不清楚png比jpg好在哪了，以及你为啥做了返回jpg的版本还要弄png的，不过下个版本会试试也解码png。

**Comment by LoveJudgement** [comment]
感谢理解。

主要还是希望能进行精确比较。有些情况自带模板是匹配不上的（notably，出击过程中匹配文字的比如 `Sortie_Formation` 和 `Sortie_SelectWayPoint`）。这个东西已知至少会因为硬件加速、系统字体 fallback、渲染方法（指 MacType 及其使用的配置）的影响导致长得不一样。于是我进行了好几次本地抠模板替换的操作。
我认为这种本地截图本地使用的场景更合适直接精确匹配，可以有效的避免各类灵异问题疑难杂症。

而与之相对的，JPG 的优势几乎仅仅对需要经由带宽有限链路的环境有（相当有限的）意义。说实话我认为这种 use case 的使用范围过于狭窄。

有一个相关的建议，不过实现估计会非常麻烦所以只是顺带一提：提供一个选项直接使用精确匹配。对于使用 100% 缩放的用户，精确匹配可以提高效率 + 减少疑难杂症（虽然还会存在 Chrome 开/关硬件加速导致像素级区别的问题，不过只要不匹配文字应该可以通过改浏览器设置解决）。如果有这个功能的话我会非常愿意用的。

**Comment by KanaHayama** [comment]
你说的因为字体匹配不上，正确的解决方法应该是换一个特征的模板。我有这个计划，但一直没有做（懒）。
精确匹配是不可能的，不仅因为你说的设置导致显示不同。很多地方是动画，只能模糊匹配。再加上用户普遍不带脑子，加上这种功能反而要费更多口舌。
