### ISSUE TITLE
神威改母装备换错

### ISSUE THREAD

**Issue by kcpsreport** [KanaHayama/KanCollePlayerSimulator#59]
经检查，神威改母可装备“零式水中听音机”

**Comment by glanzchristian** [comment]
新实装的球磨改二丁也有换装错误

**Comment by KanaHayama** [comment]
问题是否已经解决？

**Comment by KanaHayama** [comment]
> 新实装的球磨改二丁也有换装错误

需要提供是哪个装备出错。我刚测试没发现任何问题。

**Comment by kcpsreport** [comment]
上周我通过朋友找到是谁呼叫舰队的作者汇报了数据库的错误：
一个是神威改母（零听），一个是球磨改二丁（之前数据库错误列出可装备水侦类）。
刚跑了看了一下现在两个问题都得到修正啦。
