### ISSUE TITLE
基础编成单个位置多个同名但不同ID船无法更换（微博上发过，但这里有截图）

### ISSUE THREAD

**Issue by ArchmageTony** [KanaHayama/KanCollePlayerSimulator#6]
软件：1.2.2.2
POI版本：9.0.3
操作系统：Windows 7
描述：
看过奏大写的使用说明与已知问题，好像没有找到解决方法所以写一下，微博上也发过（ID：CrowAria），这里的增加了截图。
1、在基础遍成中如果一个位置放多个同名但是ID不同的船的话他会判断成重复的船而直接跳过不更换。修改其中的跳过条件无效，感觉应该不是我设置的问题。
编成设置：
![20181022105901](https://user-images.githubusercontent.com/19744053/47276439-9513d000-d5e9-11e8-8395-1c22ee1240d4.png)
log输出：
![20181021143221](https://user-images.githubusercontent.com/19744053/47276354-0f902000-d5e9-11e8-9730-03ddf05efe28.png)
***
2、偶尔会出现通信中断的情况，有可能是自己电脑的问题？（暂时没有在其它电脑上测试过）原因未知，修改过端口，且确保端口无冲突，限制CPU为1，无杀毒软件防火墙等软件。报错后立刻尝试使用浏览器访问截图地址正常，之后重新运行脚本也无异常。频率上我大概每天使用4-6个小时，平均2-3天左右出现一次，这个问题很迷。
报错与log输出（这次是在出击过程中出现的）：
![20181022104215](https://user-images.githubusercontent.com/19744053/47276488-d7d5a800-d5e9-11e8-82d1-f9038c882bf1.png)
![20181022104331](https://user-images.githubusercontent.com/19744053/47276489-d86e3e80-d5e9-11e8-81c2-e2cc49a7b1c6.png)

**Comment by KanaHayama** [comment]
第一个问题，我更新了1.2.2.3版本，估计是解决了。改动很小，应该不会错，懒得测试了。
第二个问题，完全不清楚是怎么回事，你单独开一个issue吧，不要把问题放到一起。
