### ISSUE TITLE
排查発現不存在的裝備

### ISSUE THREAD

**Issue by riserise1992** [KanaHayama/KanCollePlayerSimulator#62]
遠征DD在裝備大発時一直會選中錯誤的裝備，排查后発現一根不存在的7.7mm機銃。
<img width="233" alt="屏幕截图 2021-04-02 020305" src="https://user-images.githubusercontent.com/81771553/113335577-b56a1c00-9357-11eb-9e5c-8e3e34070c50.png">
<img width="310" alt="屏幕截图 2021-04-02 020348" src="https://user-images.githubusercontent.com/81771553/113335589-b9963980-9357-11eb-946e-fd0f161520bd.png">

**Comment by KanaHayama** [comment]
请自行找出此不存在装备的ID，然后使用最新版设置页面中的选项在运行时排除此装备。
你可以使用改装执行单元，设置此名称的装备，然后运行时此不存在的装备的ID会出现在下方状态栏中。
