### ISSUE TITLE
能代改二变更装备会导致无限循环

### ISSUE THREAD

**Issue by Yuuki1314** [KanaHayama/KanCollePlayerSimulator#63]
能代改二在自动变更装备时第四装备槽识别有问题无法正确识别装备导致forever loop

**Comment by KanaHayama** [comment]
我不清楚你指的foever loop是什么意思。新船换装备出错问题时的排查步骤已经在FAQ中给出，请按照步骤排查。
遇到问题请先看FAQ而不是从各个渠道对我进行信息轰炸，谢谢合作。

**Comment by Yuuki1314** [comment]
看了FAQ啊这个无解。因为不知道怎么让脚本去换阿贺野级的装备所以没法用自带脚本排查。但是可以确定整个阿贺野级改二都出现了这个问题。似乎是第三或者第四装备槽无法被正确识别到而且影响的仅仅是自动刷闪脚本。

**Comment by Yuuki1314** [comment]
其他4槽甚至5槽轻巡都不会出现类似的情况具体症状就是已经换上了正确的装备但是还是继续换同样的装备。

**Comment by KanaHayama** [comment]
已经定位原因，是因为《是谁呼叫舰队》的数据结构改了，导致换装备失败。已经针对这个问题发布了新版本。
