### ISSUE TITLE
联合舰队导致其他编队的换船出现问题

### ISSUE THREAD

**Issue by kcpsreport** [KanaHayama/KanCollePlayerSimulator#64]
现象：编成联合舰队的时候，3，4队的编成展开会在展开后卡住不动，控制台中可见“联合舰队因编成变更被解除”报告（实际上没有解除）
如果没有编成联合舰队，虽然也会产生这条报告，但是可以顺利编成展开并发出远征。

怀疑是不是因为编成了联合舰队导致覆盖了游击舰队字样导致的？

**Comment by KanaHayama** [comment]
我没开始打活动，不知道这次游击部队的界面啥样，目前我没看懂问题描述。

**Comment by kcpsreport** [comment]
啊，我重新描述一下：

首先问题发生在“已经编成了联合舰队”的情况下。此时3队或者4队的远征闪用完要更换成另外一队船的时候，会卡死在编成步骤上。卡死的具体现象是3队或4队船已经全部更换为有闪的船了，但是无法进入下一步，也没有任何报错弹窗。此时查看控制台输出，会看到一条“联合舰队因编成变更被解除”（但是上述的所有操作和现象都不涉及联合舰队，这条报告不应该出现？）

但是只要没有编成联合舰队（或者手动解除联合舰队的编成），就不会卡住，能够正常更换3/4队的船。考虑到这个现象，怀疑是由于图像遮挡造成的。
![combine](https://user-images.githubusercontent.com/72516361/120082741-2ed38000-c0f7-11eb-96d2-34c0b58e5516.png)这是没有编成联合舰队的图
![combine2](https://user-images.githubusercontent.com/72516361/120082754-3f83f600-c0f7-11eb-8ab2-8897d411f7c1.png)这是编成联合舰队的图

另外有个BUG是编成运输舰队的时候判定不太对，手动能够编成运输队的船会报错提示“当前舰队配置不符合组成输送护卫部队的条件，组成联合舰队失败”

**Comment by KanaHayama** [comment]
知道了，等我打到那一部分再调试。不过因为它这个游击部队算是挺大的改动了，影响面应该是不小。有影响的部分先避开就好了。

**Comment by KanaHayama** [comment]
已经发布1.4.4.0
