### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by cul9** [KanaHayama/KanCollePlayerSimulator#68]
It doesn't work.
I bought a new computer, but kcps is not running
Netcore 3.1.1, NetFramework 4.8, and .Net 5.0 were all installed.
It only repeatedly prompts  to install Netcore 3.1.0.
(This is a 64-bit computer)

**Comment by cul9** [comment]
installed the kcps-terminal.
I mean 'kcps' is not running.

**Comment by KanaHayama** [comment]
That prompt is from Microsoft, so I do not know how it detects your .net core runtime installation.
Try the latest .net 5 from this [link](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.7-windows-x64-installer).

**Comment by KanaHayama** [comment]
The above link is for .NET 5 **Desktop** runtime, and it is different from the regular .NET 5 runtime. When the manual is written, only one runtime is provided that is the Desktop runtime, I do not know why Microsoft splits it into 2 versions again after that.

**Comment by KanaHayama** [comment]
KCPS now uses .NET 6. I am closing this issue.
