### ISSUE TITLE
线上脚本一部分能正常使用，一部分初始化失败

### ISSUE THREAD

**Issue by yikaa** [KanaHayama/KanCollePlayerSimulator#69]
`使用奏大的预设脚本，py脚本是在线上的，但是一部分初始化是没问题的，一部分提示初始化失败，导致无法关联自动运行
`# FAILED TO INITIALIZE THE FOLLOWING SCRIPT / FILE / URI
'''
https://kcps.info/public-files/Python脚本/附加/远征调度.py
查看此链接可以正常访问

**Comment by KanaHayama** [comment]
说明脚本载入配置并读取这个网址的时候网络有问题，所以它读取失败了。关掉刚打开的配置，然后再开一遍，直到没有问题即可。
