### ISSUE TITLE
偶尔出现通信中断的问题（单开Issue）

### ISSUE THREAD

**Issue by ArchmageTony** [KanaHayama/KanCollePlayerSimulator#7]
软件：1.2.2.3
POI版本：9.0.3
操作系统：Windows 7
描述：
## 2018-10-24更新：
今天出击的时候又出现了这种情况，但是发现了几个问题，出现通信中断的时候我还是在出击的地图中（这次跟上次好像都是在进击跟撤退的选择那里），但是在log日志上面已经执行`基础补给`的单元了，会不会是实际上不是通信的错误而是其它的问题但是报错报的是通信的错误？今天报错的顺序与上次相同：
![20181024164824](https://user-images.githubusercontent.com/19744053/47418865-9a217c80-d7ad-11e8-886e-76de90a47ba9.png)
我的关联出击顺序是这样设置的：
关联了`基础解体`→`基础入渠`→`基础补给`→`单次出击`→`基础补给`→`基础入渠`
这里面的相同单元是重复使用的，主要是因为自己有时候打完了忘了补给，防止脚本出击前没补给所以加了两次补给跟入渠。
正常的一次执行顺序log输出：
这里的`基础补给`单元安排返回母港界面跟执行单元`单次出击`时间就是不相同的，但是上面那次是同时触发的，会不会跟这个有关系？
![20181024171519](https://user-images.githubusercontent.com/19744053/47420287-a6f39f80-d7b0-11e8-9421-f2e70c1588d8.png)

***
## 2018-10-21描述
偶尔会出现通信中断的情况，有可能是自己电脑的问题？（暂时没有在其它电脑上测试过）原因未知，修改过端口，且确保端口无冲突，限制CPU为1，无杀毒软件防火墙等软件。报错后立刻尝试使用浏览器访问截图地址正常，之后重新运行脚本也无异常。频率上我大概每天使用4-6个小时，平均2-3天左右出现一次，这个问题很迷。
报错与log输出（这次是在出击过程中出现的）：
![20181022104215](https://user-images.githubusercontent.com/19744053/47418675-2ed7aa80-d7ad-11e8-9082-f6c634f2d6d5.png)
![20181022104312](https://user-images.githubusercontent.com/19744053/47418676-2f704100-d7ad-11e8-81ca-83030b5e010b.png)

**Comment by KanaHayama** [comment]
1.2.3.0版本会有更详细的错误描述，请更新后再试

**Comment by ArchmageTony** [comment]
> 1.2.3.0版本会有更详细的错误描述，请更新后再试

最近在外出，可能得等一段时间才能尝试了，如果还有问题的话我再在这里写出来。

**Comment by ArchmageTony** [comment]
> 1.2.3.0版本会有更详细的错误描述，请更新后再试

测试了几天好像没再出现这个问题了，先把这个issues关了吧

**Comment by ArchmageTony** [comment]
> 1.2.3.0版本会有更详细的错误描述，请更新后再试

我又回来了。。。本身以为不会再出现了。。。结果又出来了，这次有详细的输出了。
版本是1.2.4.0，今天刚开始使用的1.2.4.0，之前一直用的是1.2.3.0好像没出现过，但是因为用的时间不多所以也不是很确定。
虽然写的是被中止，但是我也没有安装或者开启防火墙之类的东西。。。。并且我电脑也重装过一遍系统了，应该是能排除说之前说可能是自己系统的问题。。。。
![image](https://user-images.githubusercontent.com/19744053/48695752-f21b9980-ec1a-11e8-9c7f-2223e4535c13.png)

**Comment by KanaHayama** [comment]
目前的版本上还有这个问题吗？

**Comment by ArchmageTony** [comment]
> 目前的版本上还有这个问题吗？

已经没问题了，忘记关了
