### ISSUE TITLE
第三舰队游击部队进入活动图后无法自动选择阵型

### ISSUE THREAD

**Issue by sekurodesu** [KanaHayama/KanCollePlayerSimulator#72]
如题，手动选择后战斗完毕也不会自动点击游戏界面进入下一个战斗点

**Comment by sekurodesu** [comment]
奏大这个问题还是没法解决吗？打到E3了也还是这样，没法自动选择阵型

**Comment by KanaHayama** [comment]
我昨天刚开始打活动，打到E2了，没遇到你说的问题，其他用户也没有人报告过类似问题。请确认你使用的是原版的KCPS。
