### ISSUE TITLE
循环条件中加入士气条件或许可以增加刷闪效率

### ISSUE THREAD

**Issue by OrangesDay** [KanaHayama/KanCollePlayerSimulator#78]
循环条件中加入士气条件或许可以增加刷闪效率

**Comment by KanaHayama** [comment]
能详细说一下吗？
什么样的条件可以怎样提高效率？

**Comment by OrangesDay** [comment]
在 总控 自动停止条件中 加入 士气 大于等于 xx值 后停止，可以省去每条舰船 士气不同值时 造成的重复操作。
如表述得不清楚，请提出。

**Comment by KanaHayama** [comment]
抱歉我才看到上面这个回复。
我没有理解你说的这个选项会有什么帮助。每次刷闪只能刷给旗舰，并不需要关心伴随舰的士气，没有判断整个舰队的每一条船士气是否达到要求的必要。
如果这里说的“每条船”指的是你在编成单元里设置的候选船，那么这个选项就不现实。因为“关联出击”无权也不应当管理“基础编成”的内部实现。

**Comment by OrangesDay** [comment]
当 旗舰 的士气值为大于等于一定值时，则停止循环。自己用python做好了模块加进去后老出BUG（如：循环不停止、和POI contecting lost等问题）

**Comment by KanaHayama** [comment]
已实现
