### ISSUE TITLE
增加或点击已有的展开编成单元，程序出错

### ISSUE THREAD

**Issue by karegyudon** [KanaHayama/KanCollePlayerSimulator#83]
**Version**
1.4.6.0

**Describe the bug**
增加或点击已有的展开编成单元，程序出错

**Frequency of the bug**
每次都出现

**To Reproduce**
1.点击已有的配置或创建一个新的配置
2.点击配置中现有的展开编成单元，或新增一个展开编成单元
3.出现错误提示（如截图）

**Expected behavior**
应该正常显示单元的配置界面

**Screenshots**
![Snipaste_2022-03-27_22-36-31](https://user-images.githubusercontent.com/22168767/160286811-1493dad9-1fe1-4a01-8625-59970dd99f9c.png)

**Environment (please complete all of the following information):**
 - OS: Windows 10
 - OS version [10.0.]
 - OS language: [Simplified Chinese]
 - Browser: [poi]
 - Browser version: [10.8.0]
 - KCPS bowser plugin version: [1.4.6]
 - Is KCPS registed: [Yes]
 - Game account level: [120]

**Additional context**
none

**Comment by karegyudon** [comment]
补充一下，只要不点击这个执行单元，可以被正常调用和触发，并不会出错，只有点击到这类执行单元才会出错。

**Comment by KanaHayama** [comment]
谢谢反馈。该问题大约在两星期前已经添加到《已知问题了》。请查阅。
