### ISSUE TITLE
请问一下夏活（春活）的地图更新文件有什么地方能获取么

### ISSUE THREAD

**Issue by qq2813798515** [KanaHayama/KanCollePlayerSimulator#87]
QQ等级不够加不了群，有没有什么地方能下载地图文件的么

**Comment by s410196** [comment]
https://github.com/KanaHayama/KanCollePlayerSimulator/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

期间限定海域 有教你如何自己抓圖 自己設定

**Comment by KanaHayama** [comment]
以前一直在开服不久后提供数据的大佬退坑了，所以以后不会再提供期间限定海域的差分。请自行制作，步骤在《使用说明》中已经提供了。
