### ISSUE TITLE
裝備更換錯誤-5inch連装砲(副砲配置) 集中配備 裝備列表問題

### ISSUE THREAD

**Issue by sunhomeboy5566** [KanaHayama/KanCollePlayerSimulator#88]
本次活動2022年 梅雨イベント『[血戦！異聞坊ノ岬沖海戦]突破報酬-5inch連装砲(副砲配置) 集中配備

5inch連装砲(副砲配置) 集中配備 有 1 个錯誤

如附圖 (https://imgur.com/tWt1Bxa)

(https://imgur.com/e22QUQ1)

5inch連装砲(副砲配置) 集中配備 無法裝備至 DD/CL/CVL/AV 系列 但是換裝列表有，導致裝備更換錯誤

目前簡易解決方法 把5inch連装砲(副砲配置) 集中配備 裝備到你不常用的艦娘身上

**Comment by kimibsb** [comment]
但是如果从其他船上取装备时，还是会识别到这个装备，然后换装失败
只能等修复或者自己改本地文件

**Comment by KanaHayama** [comment]
已解决
