### ISSUE TITLE
你好 1.2.6.1 關聯出擊中等待選項遇到一些問題

### ISSUE THREAD

**Issue by man4781747** [KanaHayama/KanCollePlayerSimulator#9]
等待到所有選中修復渠空閒的選項 選取了之後似乎沒有效果 
我有船正在入渠但她程式沒有依入渠時間來執行
觀看入渠頁面下方的狀態信息攔時 確定程式是有紀錄入渠剩餘時間的

**Comment by KanaHayama** [comment]
1.2.7.0中已经修复
