### ISSUE TITLE
使用cuda模板匹配模块时，会间歇性卡顿

### ISSUE THREAD

**Issue by sekurodesu** [KanaHayama/KanCollePlayerSimulator#90]
如题，间隔大概是半分钟到一分钟之间就会有一次，很频繁，使用opencv模板匹配模块时就没有卡顿的问题，卡顿时如果只是单开砍口累下图这个进程的GPU占用会从0.5%飙升到20%左右，如果还开了网页视频其他的话会从0.5%瞬间飙升到30-50%左右，而且卡顿不是一下子，会持续大概好几秒到10秒，是什么原因呢？
![无标题](https://user-images.githubusercontent.com/51750095/180630165-66207b3b-1ac7-4c9b-94fc-d3ce3243bb2f.png)

**Comment by KanaHayama** [comment]
你显卡带宽不够吧，CUDA方法没有优化，带宽会成为瓶颈。我用的挺老的PCIe 3.0 * 16的1080Ti，没遇到你说的问题。

**Comment by sekurodesu** [comment]
啊这样，我用的是750，确实是太低端的显卡了，那后续有优化cuda的计划吗？

**Comment by KanaHayama** [comment]
没有

**Comment by sekurodesu** [comment]
好吧
