### ISSUE TITLE
更新到最新版以后，同时执行远征和出击任务时，远征任务会一直不执行

### ISSUE THREAD

**Issue by sekurodesu** [KanaHayama/KanCollePlayerSimulator#93]
如题，远征和出击同时运行的时候，当远征回来以后，会一直处于执行状态，然后继续执行出击任务，远征发不出去
如果作者你暂时没那么快能修好这个BUG，能不能把1.4.6.1版本的压缩包也上传一下，我下回老版去用，不然这个BUG太影响游戏了

**Comment by KanaHayama** [comment]
1.4.6.1已经传上去了。
我自己测试没遇到这个问题，也还没有其他人说有问题。
请问你用的是哪个远征模块？是自己编写的还是我发的范例？同时运行的出击是什么出击？是范例的出击还是你自己编写的？

**Comment by sekurodesu** [comment]
就是基础远征和关联出击单次出击那些，是自己添加进去的，但是是以前就一直在用的，之前没问题，直接用1.4.6.2覆盖下去后就出了问题了

**Comment by KanaHayama** [comment]
有log消息或许可以定位问题。如果你没有兴趣确定哪里不对，你可以直接关闭这个issue。
