### ISSUE TITLE
获取数据失败：浏览器插件内部错误

### ISSUE THREAD

**Issue by Mattz-P** [KanaHayama/KanCollePlayerSimulator#94]
**Version**
The KancollePlayerSimulator Kai version: 1.4.6.2
POI: 10.9.2

**Describe the bug**
![image](https://user-images.githubusercontent.com/33806410/199581156-89f69845-0a51-410b-b34e-0fb70166ef50.png)
```
2022-11-02 12:12:48,824 ERROR “刷闪”中的“GIO”报错，已自动禁用：
    关联出击前改装执行单元执行时出现了错误，因未设置相关错误处理方式而无法继续
        获取数据失败：浏览器插件内部错误
2022-11-02 12:12:48,860 INFO  已取消任务"返回提督室"
2022-11-02 12:12:48,861 ERROR “刷闪”中的“基础变更装备”报错，已自动禁用：
    执行变更装备时检查到错误
        获取数据失败：浏览器插件内部错误
```
```
2022-11-02 12:12:28,739 ERROR “精鋭レべ5-3”中的“关联出击”报错，已自动禁用：
    关联出击前改装执行单元执行时出现了错误，因未设置相关错误处理方式而无法继续
        获取数据失败：浏览器插件内部错误
2022-11-02 12:12:28,779 ERROR “精鋭レべ5-3”中的“基础变更装备”报错，已自动禁用：
    执行变更装备时检查到错误
        获取数据失败：浏览器插件内部错误
```
Issues occured when switching equipments.

Example of a simple equipment change that failed:
![image](https://user-images.githubusercontent.com/33806410/199582198-917ac87a-1c59-4c91-8b36-541f126b14c2.png)

So far, I've tried reinstalling poi-plugin-kcps-terminal.

**Frequency of the bug**
Pretty much everytime when switching equipments. 

**Environment (please complete all of the following information):**
 - OS: Win 10
 - OS version 19043.2130
 - OS language: English-US
 - Browser: POI
 - Browser version: 10.9.2
 - KCPS bowser plugin version: 1.4.6
 - Is KCPS registed: Yes
 - Game account level: 104

**Additional context**

**Comment by Mattz-P** [comment]
Fixed with using arichived POI version 10.6; if @KanaHayama not interested in updating with newer poi version, feel free to close this.

**Comment by KanaHayama** [comment]
Only a portion of the user's machines have this error message.  Most users, including me, do not have that error using the latest poi.
Since I do not have that error, and error messages are shown in poi's console, users do not want to help me to get the error message. So, I do not have access to it, so I do not know what happened.
It will be great if you can help identify the problem. Open poi's console and get a screen shot of the error message from kcps poi plugin is enough. Thank you!

**Comment by Mattz-P** [comment]
Hmm, as I was trying to provoke the issue today, Poi updated the [newest patch](https://github.com/KanaHayama/poi-plugin-kcps-terminal/commit/017fbb566ce2b4849b50fceabffd8b4512a3508e) for KCPS-terminal, and it seems that 1.4.7 fixed the problem. I couldn't make it report exceptions anymore.
