### ISSUE TITLE
更换出击船只时候的一个BUG

### ISSUE THREAD

**Issue by kcpsreport** [KanaHayama/KanCollePlayerSimulator#96]
现象是
当某些可能会导致F5的出击(如6-1，4-2下路，但我不能肯定就是这样，只是我这边恰好都出在这个条件下)和刷闪队交替出击的时候，当刷闪队首次需要更换到DD的时候(包括1CL若干DD)，船只类型的标签会全部点亮并卡住，长时间等待也没有反应。手动点击关闭全部标签后即可正常执行，后续也不会卡住。不是间隔出击，直接开始刷闪则没有问题。因为一定是第一次要换DD时候出现这个问题，感觉不是按钮的阈值问题。
更新1.5以来已出现4次相同情况。

另一个小问题是设定了一个刷闪后触发修理，修理为1队旗舰和其他，偶尔会漏掉一条船不入渠。1.5之前相同配置无此现象。
更新1.5以来已出现2次相同情况。

**Comment by KanaHayama** [comment]
第一个问题我这里遇不到，怀疑是显示和我这里不一样，然后导致阈值不适用了，我还在收集类似的bug信息。
请问你使用的是Win10还是Win11？有没有调整过什么显示设置，比如HDR，色彩伽马，“最佳性能”视觉效果？使用的是什么显示器？游戏画面的缩放是%多少？kcps的poi插件上的jpeg质量设置的是多少？

第二个问题我还没听说过类似的反馈，不知道具体发生了什么。

**Comment by kcpsreport** [comment]
WIN10全默认
WIN缩放100%，POI缩放100%，KCPS插件缩放1，JPEG质量80%
阈值的话我也怀疑过是不是那个小三角的阈值，但工具里好像没有那个小三角的模板
尝试看过Organize_ShipSelector_EventRestriction_None可以匹配

第二个问题就是比如我给6船或12船刷闪，刷完后触发一个入渠模块（设置是过去用的一直没问题），但现在只会入渠5船或11船就显示“尚未被触发或自动停止”

**Comment by kcpsreport** [comment]
试了一天，没有再出现这两个问题，先关闭了
